/* Algorithms adapted from Unlock Music CLI v0.2.12 (MIT) and Unlock Music Web (MIT).
 * See THIRD_PARTY_NOTICES.md. File IO is bounded and runs only in a disposable Worker. */
import CryptoJS from 'crypto-js';
import QmcModule from '@xhacker/qmcwasm/QmcWasmBundle.js';
import KgmModule from '@xhacker/kgmwasm/KgmWasmBundle.js';
import initSql from 'sql.js/dist/sql-wasm.js';
import sqlBinary from 'sql.js/dist/sql-wasm.wasm';
const CHUNK=512*1024,MAX=64*1024*1024;
const text=b=>new TextDecoder().decode(b),wa=b=>CryptoJS.lib.WordArray.create(b);
const bytes=w=>Uint8Array.from({length:w.sigBytes},(_,i)=>(w.words[i>>>2]>>>(24-(i%4)*8))&255);
const md5=b=>bytes(CryptoJS.MD5(wa(b)));
const hex=s=>Uint8Array.from(s.match(/../g),x=>parseInt(x,16));
function check(ok,message='DAMAGED AUDIO FILE'){if(!ok)throw Error(message);}
function aes(data,key,iv){check(data.length>0&&data.length%16===0,'INVALID ENCRYPTED BLOCK');const plain=bytes(CryptoJS.AES.decrypt({ciphertext:wa(data)},wa(key),{mode:iv?CryptoJS.mode.CBC:CryptoJS.mode.ECB,padding:CryptoJS.pad.NoPadding,...iv?{iv:wa(iv)}:{}}));if(!iv){const pad=plain.at(-1);check(pad>=1&&pad<=16&&plain.slice(-pad).every(x=>x===pad),'INVALID FILE KEY');return plain.slice(0,-pad);}return plain;}
async function read(file,start,len){check(Number.isSafeInteger(start)&&Number.isSafeInteger(len)&&start>=0&&len>=0&&start+len<=file.size);return new Uint8Array(await file.slice(start,start+len).arrayBuffer());}
export function sniff(b){const s=text(b.subarray(0,12));if(s.startsWith('fLaC'))return 'flac';if(s.startsWith('OggS'))return 'ogg';if(s.startsWith('RIFF')&&s.slice(8)==='WAVE')return 'wav';if(s.slice(4,8)==='ftyp')return 'm4a';if(s.startsWith('ID3')||(b[0]===255&&(b[1]&0xe0)===0xe0&&(b[1]&6)!==0))return 'mp3';if(b[0]===255&&(b[1]&0xf6)===0xf0)return 'aac';if(s.startsWith('FORM'))return 'aiff';if(s.startsWith('.snd'))return 'au';if(b[0]===0x1a&&b[1]===0x45&&b[2]===0xdf&&b[3]===0xa3)return 'webm';return null;}
const mime={mp3:'audio/mpeg',flac:'audio/flac',ogg:'audio/ogg',m4a:'audio/mp4',wav:'audio/wav',aac:'audio/aac',aiff:'audio/aiff',au:'audio/basic',webm:'audio/webm'};
async function stream(file,start,end,transform,onProgress,meta={}){check(end>start);const parts=[];let ext;for(let p=start;p<end;p+=CHUNK){const b=await read(file,p,Math.min(CHUNK,end-p));transform(b,p-start);if(!ext){ext=sniff(b);check(ext,'UNSUPPORTED FORMAT OR MISSING KEY');}parts.push(new Blob([b]));onProgress((p-start+b.length)/(end-start));}return {blob:new Blob(parts,{type:mime[ext]}),ext,meta,decrypted:true};}
async function ncm(file,progress){const header=await read(file,0,10);check(text(header.subarray(0,8))==='CTENFDAM','INVALID NCM HEADER');let p=10;async function block(){const n=new DataView((await read(file,p,4)).buffer).getUint32(0,true);p+=4;check(n<=2*1024*1024);const b=await read(file,p,n);p+=n;return b;}
 const raw=await block();for(let i=0;i<raw.length;i++)raw[i]^=0x64;const plain=aes(raw,hex('687a4852416d736f356b496e62617857'));check(text(plain.subarray(0,17))==='neteasecloudmusic','INVALID NCM KEY');const key=plain.subarray(17);check(key.length>0);const box=Uint8Array.from({length:256},(_,i)=>i);for(let i=0,j=0;i<256;i++){j=(j+box[i]+key[i%key.length])&255;[box[i],box[j]]=[box[j],box[i]];}const mask=box.map((_,i)=>{const a=(i+1)&255,b=box[a];return box[(b+box[(a+b)&255])&255];});
 const encryptedMeta=await block();let meta={};if(encryptedMeta.length){try{const m=encryptedMeta.map(x=>x^0x63);const decoded=text(aes(bytes(CryptoJS.enc.Base64.parse(text(m.subarray(22)))),hex('2331346c6a6b5f215c5d2630553c2728')));let info=JSON.parse(decoded.slice(decoded.indexOf(':')+1));info=info.mainMusic||info;meta={title:info.musicName,artist:Array.isArray(info.artist)?info.artist.map(a=>Array.isArray(a)?a[0]:a).join(', '):info.artist,album:info.album};}catch{/* Audio remains usable without metadata. */}}
 const coverHeader=await read(file,p,13),v=new DataView(coverHeader.buffer),frame=v.getUint32(5,true),size=v.getUint32(9,true);check(frame>=size&&p+13+frame<=file.size);if(size>0&&size<=2*1024*1024){const image=await read(file,p+13,size),type=image[0]===255?'image/jpeg':image[0]===137?'image/png':null;if(type)meta.artworkBlob=new Blob([image],{type});}p+=13+frame;
 return stream(file,p,file.size,(b,offset)=>{for(let i=0;i<b.length;i++)b[i]^=mask[(offset+i)&255];},progress,meta);
}
export async function readKggKeys(file){check(file.size<=32*1024*1024,'KEY DATABASE TOO LARGE');const b=await read(file,0,file.size);check(b.length>=1024);if(text(b.subarray(0,16))!=='SQLite format 3\0'){check(b.length%1024===0,'INVALID KGG DATABASE');const base=hex('1d613145b247bf7f3d189672144fe4bf0000000073416c54');for(let at=0,page=1;at<b.length;at+=1024,page++){const material=base.slice();new DataView(material.buffer).setUint32(16,page,true);const key=md5(material),ivData=new Uint8Array(16),view=new DataView(ivData.buffer);let seed=page+1;for(let i=0;i<16;i+=4){let n=(Math.imul(seed,0x9ef4)-Math.imul(Math.floor(seed/0xce26),0x7fffff07))>>>0;if(n&0x80000000)n=(n+0x7fffff07)>>>0;seed=n;view.setUint32(i,seed,true);}const iv=md5(ivData);if(page===1){const expected=b.slice(16,24);b.copyWithin(16,8,16);const result=aes(b.slice(16,1024),key,iv);check(expected.every((x,i)=>x===result[i]),'INVALID KGG DATABASE KEY');b.set(result,16);b.set(new TextEncoder().encode('SQLite format 3\0'));}else b.set(aes(b.slice(at,at+1024),key,iv),at);}}
 const SQL=await initSql({wasmBinary:sqlBinary});const db=new SQL.Database(b);try{const rows=db.exec("SELECT EncryptionKeyId, EncryptionKey FROM ShareFileItems WHERE EncryptionKey IS NOT NULL AND EncryptionKey != ''");const keys=Object.create(null);for(const row of rows[0]?.values||[])keys[String(row[0])]=typeof row[1]==='string'?row[1]:text(row[1]);check(Object.keys(keys).length,'NO KEYS IN DATABASE');return keys;}finally{db.close();}}
async function wasmDecode(file,ext,progress,ekey=null,start=0){const kgm=['kgm','kgma','vpr'].includes(ext);const mod=await (kgm?KgmModule:QmcModule)({print:()=>{},printErr:()=>{}});const size=2*1024*1024,ptr=mod._malloc(size);check(ptr,'DECODER MEMORY LIMIT');try{let init;if(ekey){const key=new TextEncoder().encode(ekey);check(key.length<65536,'INVALID KEY');init=new Uint8Array(key.length+4);init.set(key);new DataView(init.buffer).setUint32(key.length,key.length,true);}else init=kgm?await read(file,0,Math.min(size,file.size)):await read(file,Math.max(0,file.size-size),Math.min(size,file.size));mod.writeArrayToMemory(init,ptr);const skip=mod.preDec(ptr,init.length,kgm?ext:'.'+(ekey?'mflac':ext));check(Number.isInteger(skip)&&skip>=0,ekey?'INVALID KEY':'KEY REQUIRED / UNSUPPORTED VERSION');const begin=kgm?skip:start,end=kgm||ekey?file.size:file.size-skip;check(begin>=0&&end<=file.size&&end>begin);
 return await stream(file,begin,end,(b,offset)=>{mod.writeArrayToMemory(b,ptr);const n=mod.decBlob(ptr,b.length,offset);if(!kgm)check(n===b.length,'DECRYPTION FAILED');b.set(mod.HEAPU8.subarray(ptr,ptr+b.length));},progress);
 }finally{mod._free(ptr);}}
export async function decryptAudio(file,{onProgress=()=>{},keys={}}={}){check(file.size>16&&file.size<=MAX,'USE AUDIO UNDER 64 MB');let ext=file.name.toLowerCase().split('.').pop();if(/\.(kgm|vpr)\.flac$/i.test(file.name))ext=file.name.toLowerCase().split('.').at(-2);const head=await read(file,0,Math.min(1024,file.size));const plain=sniff(head);if(plain)return {blob:new Blob([file],{type:mime[plain]}),ext:plain,meta:{}};
 if(ext==='ncm')return ncm(file,onProgress);
 if(ext==='kwm'){check(['yeelion-kuwo-tme','yeelion-kuwo\0\0\0\0'].includes(text(head.subarray(0,16))),'UNSUPPORTED KWM VERSION');const value=new DataView(head.buffer).getBigUint64(24,true).toString(),seed='MoOtOiTvINGwd2E6n0E1i7L5t2IoOoNk',mask=Uint8Array.from({length:32},(_,i)=>seed.charCodeAt(i)^value.charCodeAt(i%value.length));return stream(file,1024,file.size,(b,offset)=>{for(let i=0;i<b.length;i++)b[i]^=mask[(offset+i)%32];},onProgress);}
 if(['kgm','kgma','vpr','kgg'].includes(ext)){check(head.length>=72);const expected=hex(ext==='vpr'?'0528bc96e9e45a4391aabdd07af53631':'7cd532eb86027f4ba8afa68e0fff9914');check(expected.every((x,i)=>x===head[i]),'INVALID KUGOU HEADER');const v=new DataView(head.buffer),start=v.getUint32(16,true),version=v.getUint32(20,true);check(start>=60&&start<file.size);if(version===5){const len=v.getUint32(68,true);check(len>0&&len<=512&&72+len<=start);const id=text(await read(file,72,len)),key=keys[id];check(key,'SELECT KGG + KGMusicV3.db TOGETHER');return wasmDecode(file,'qmc',onProgress,key,start);}if(version===3){check(v.getUint32(24,true)===1,'UNSUPPORTED KGM KEY SLOT');const reverse=b=>{const d=md5(b),r=new Uint8Array(16);for(let i=0;i<16;i+=2){r[i]=d[14-i];r[i+1]=d[15-i];}return r;},slot=reverse(hex('6c2c2f27')),key=new Uint8Array(17);key.set(reverse(head.subarray(44,60)));key[16]=0x6b;return stream(file,start,file.size,(b,offset)=>{for(let i=0;i<b.length;i++){const p=offset+i;let x=b[i]^key[p%17];x^=x<<4;b[i]=x^slot[p%16]^p^(p>>>8)^(p>>>16)^(p>>>24);}},onProgress);}check(version===2,'UNSUPPORTED KGM VERSION');return wasmDecode(file,ext,onProgress);}
 if(ext==='uc')return stream(file,0,file.size,b=>{for(let i=0;i<b.length;i++)b[i]^=0xa3;},onProgress);
 const key=keys[file.name]||keys[file.name.replace(/\.[^.]+$/,'')];return wasmDecode(file,ext,onProgress,key);
}
