const {chromium}=require('/Users/a1/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const WORK='/Users/a1/Documents/Codex/2026-09-25/files-pasted-by-the-user-cassette/work';
(async()=>{
 const ctx=await chromium.launchPersistentContext('/tmp/cw-diag-profile',{executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--autoplay-policy=no-user-gesture-required'],viewport:{width:1440,height:1040}});
 const page=ctx.pages()[0]||await ctx.newPage();
 const errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 const snap=async label=>{const d=await page.evaluate(()=>{const s=window.cassetteWorld.state;return {muted:s.muted,volume:s.volume,volumeGain:s.volumeGain,playing:s.playing,transport:s.transportState,response:s.response,chain:s.audioChain};});console.log(label,JSON.stringify(d));};
 const until=async(fn,ms=90000)=>{const t=Date.now();while(Date.now()-t<ms){if(await page.evaluate(fn))return true;await page.waitForTimeout(250);}return false;};
 await page.goto('http://127.0.0.1:8765/cassette-world.html');
 await until(()=>!!window.cassetteWorld,20000);
 await page.waitForTimeout(4200);
 await snap('BOOT');
 const chooser=page.waitForEvent('filechooser',{timeout:9000});
 const at=await page.evaluate(()=>window.cassetteWorld.objectPositions['cabinetImport']);
 await page.mouse.click(at[0],at[1]);
 const fc=await chooser;
 await fc.setFiles([`${WORK}/test-1.wav`]);
 await until(()=>window.cassetteWorld.state.playlist.length===1&&!window.cassetteWorld.state.busy);
 await page.waitForTimeout(900);
 await page.keyboard.press('Escape');
 await page.waitForTimeout(2400);
 await page.keyboard.press('Space');
 await until(()=>window.cassetteWorld.state.loaded&&window.cassetteWorld.state.playing);
 await page.waitForTimeout(1600);
 await snap('PLAYING');
 const vp=await page.evaluate(()=>window.cassetteWorld.objectPositions['volume']);
 console.log('volume knob at',JSON.stringify(vp));
 await page.mouse.click(vp[0],vp[1]);
 await page.waitForTimeout(1400);
 await snap('AFTER-KNOB-CLICK');
 await page.reload();
 await until(()=>!!window.cassetteWorld,20000);
 await page.waitForTimeout(4600);
 await snap('AFTER-RELOAD');
 await page.keyboard.press('Space');
 await page.waitForTimeout(3500);
 await snap('AFTER-RELOAD-PLAY');
 console.log('ERRORS',JSON.stringify(errors));
 await ctx.close();
})().catch(e=>{console.error('FAILED',e);process.exit(1)});
