import assert from 'node:assert/strict';
import {decodeLegacy,prepareAudio,acceptsAudio,AUDIO_EXTENSIONS} from './audio-formats.js';
import {springStep,OPEN_ANGLE,KEY_REST,KEY_TRAVEL} from './physics.js';
import {MACHINE_STYLES,AD_COLLECTIONS,getMachineStyle,FOCUS_AREAS,fitFocusDistance} from './styles.js';
import {createFoley} from './foley.js';
import fs from 'node:fs';
import {selectorIndex,insideTapeZone,rotatePaperOrder,PAPER_STEP,PAPER_THICKNESS,TABLE_TOP} from './interaction.js';
let count=0;function test(name,fn){fn();count++;console.log('PASS',name);}
function ascii(view,p,t){for(let i=0;i<t.length;i++)view.setUint8(p+i,t.charCodeAt(i));}
function aiff(bits=16,codec='NONE',samples=[-.75,0,.75],channels=1){const isC=codec!=='NONE',bytes=bits/8,comm=isC?22:18,data=samples.length*bytes,total=12+8+comm+8+8+data+(data&1),buf=new ArrayBuffer(total),v=new DataView(buf);ascii(v,0,'FORM');v.setUint32(4,total-8);ascii(v,8,isC?'AIFC':'AIFF');ascii(v,12,'COMM');v.setUint32(16,comm);v.setUint16(20,channels);v.setUint32(22,samples.length/channels);v.setUint16(26,bits);v.setUint16(28,16395);v.setUint32(30,0xfa000000);v.setUint32(34,0);if(isC)ascii(v,38,codec);const ssnd=20+comm;ascii(v,ssnd,'SSND');v.setUint32(ssnd+4,data+8);const start=ssnd+16;for(let i=0;i<samples.length;i++){const p=start+i*bytes,le=codec==='sowt',sample=samples[i];if(codec.toLowerCase()==='fl32')v.setFloat32(p,sample);else if(codec.toLowerCase()==='fl64')v.setFloat64(p,sample);else if(bits===8)v.setInt8(p,Math.round(sample*128));else if(bits===16)v.setInt16(p,Math.round(sample*32768),le);else if(bits===24){let n=Math.round(sample*8388608);for(let j=0;j<3;j++)v.setUint8(p+j,(n>>((le?j:2-j)*8))&255);}else if(bits===32)v.setInt32(p,Math.round(sample*2147483648),le);}return buf;}
function au(encoding=3){const bytes=encoding===3?2:1,b=new ArrayBuffer(24+3*bytes),v=new DataView(b);ascii(v,0,'.snd');v.setUint32(4,24);v.setUint32(8,3*bytes);v.setUint32(12,encoding);v.setUint32(16,8000);v.setUint32(20,1);if(encoding===3)[-16384,0,16384].forEach((n,i)=>v.setInt16(24+i*2,n));else [255,128,0].forEach((n,i)=>v.setUint8(24+i,n));return b;}
for(const [bits,codec]of [[8,'NONE'],[16,'NONE'],[24,'NONE'],[32,'NONE'],[16,'sowt'],[24,'sowt'],[32,'fl32'],[64,'fl64']])test(`AIFF/AIFC ${bits} bit ${codec} PCM conversion`,()=>{const result=decodeLegacy(aiff(bits,codec)),v=new DataView(result.buffer);assert.equal(result.sampleRate,8000);assert.equal(result.channels,1);assert.equal(v.getInt16(44,true),-24576);assert.equal(v.getInt16(46,true),0);assert(Math.abs(v.getInt16(48,true)-24575)<=1);});
test('Stereo AIFF retains interleaving and frame duration',()=>{const d=decodeLegacy(aiff(16,'NONE',[-.5,.5,0,.25],2));assert.equal(d.channels,2);assert.equal(d.duration,2/8000);assert.equal(new DataView(d.buffer).getInt16(46,true),16384);});
test('AU PCM and mu-law produce a valid WAV',()=>{for(const enc of [3,1]){const d=decodeLegacy(au(enc)),v=new DataView(d.buffer);assert.equal(v.getUint16(20,true),1);assert.equal(v.getUint32(24,true),8000);if(enc===3)assert.equal(v.getInt16(44,true),-16384);else assert.equal(v.getInt16(44,true),0);}});
test('Compressed AIFC rejected with an explicit codec error',()=>assert.throws(()=>decodeLegacy(aiff(16,'ima4')),/COMPRESSION/));
test('Truncated PCM and invalid header are rejected',()=>{assert.throws(()=>decodeLegacy(aiff().slice(0,-2)),/TRUNCATED/);assert.throws(()=>decodeLegacy(new ArrayBuffer(12)),/DAMAGED/);});
test('Extended import list is consistent and rejects unrelated files',()=>{for(const ext of AUDIO_EXTENSIONS)assert(acceptsAudio({name:'sample.'+ext,type:''}));assert(!acceptsAudio({name:'notes.pdf',type:'application/pdf'}));});
for(const [name,min,max,k,c]of [['button',KEY_REST-KEY_TRAVEL,KEY_REST,650,45],['door',0,OPEN_ANGLE,85,18]])test(`${name} never crosses its mechanical stops with rapid reversals`,()=>{let p=max,v=0;for(let i=0;i<3000;i++){const target=i%31<14?min:max;({position:p,velocity:v}=springStep(p,v,target,[.001,.016,.033,.25,1][i%5],k,c,min,max));assert(p>=min&&p<=max);assert(Number.isFinite(v));}for(let i=0;i<300;i++)({position:p,velocity:v}=springStep(p,v,min,1/60,k,c,min,max));assert(Math.abs(p-min)<.00001);});
test('Pressed cap stays above the outer fascia',()=>{const capFront=1.63+KEY_REST-KEY_TRAVEL+.16,fasciaFront=1.34+.19+.045;assert(capFront-fasciaFront>.30);});
test('Open door has clearance below the tape insertion plane',()=>{const top=2.05+3.1*Math.cos(OPEN_ANGLE)+.14;const tapeBottom=3.59-1.12;assert(tapeBottom-top>.05);let position=0,velocity=0;for(let i=0;i<39;i++)({position,velocity}=springStep(position,velocity,OPEN_ANGLE,1/60,85,18,0,OPEN_ANGLE));assert(tapeBottom-(2.05+3.1*Math.cos(position)+.14)>.05,'Door must be clear when the 650ms insertion delay ends');});
test('Twelve valid editions preserve clearance and stable identifiers',()=>{assert.equal(new Set(MACHINE_STYLES.map(s=>s.id)).size,12);for(const style of MACHINE_STYLES){assert.equal(getMachineStyle(style.id),style);assert(style.scale.every(x=>x>.9&&x<1.1));assert(.195*style.scale[1]+.195*(1-style.scale[1])>.17);}assert.throws(()=>getMachineStyle('missing'));});
test('Every camera region fits narrow and wide viewports',()=>{for(const area of Object.values(FOCUS_AREAS))for(const aspect of [.46,.75,1.38,1.78,2.1]){const min=Math.hypot(...area.offset),distance=fitFocusDistance(area.width,39,aspect,min);const span=2*distance*Math.tan(39*Math.PI/360)*aspect;assert(span>=area.width*1.119);assert(distance<=80);}});
test('Synthesized effects schedule finite, short envelopes and respect suspended audio',()=>{const events=[];const param={setValueAtTime:(v,t)=>{assert(Number.isFinite(v)&&t>=0);},exponentialRampToValueAtTime:(v,t)=>{assert(v>0&&Number.isFinite(t));},setTargetAtTime:()=>{}};const node=()=>({connect(){return this;},disconnect(){},gain:{...param},frequency:{...param},Q:{value:0},start(t){events.push(t);},stop(t){assert(t<2);}});const ctx={state:'running',sampleRate:8000,currentTime:0,destination:{},createGain:node,createBiquadFilter:node,createBufferSource:node,createOscillator:node,createBuffer:(_c,n)=>({getChannelData:()=>new Float32Array(n)})};const fx=createFoley(ctx);for(const kind of ['key','detent','door-open','door-close','tape-in','tape-out','service-open','service-close','paper'])fx.play(kind);assert.equal(fx.events.length,9);assert(events.length>15);ctx.state='suspended';fx.play('key');assert.equal(fx.events.length,9);});
test('Each edition appears once across four paper collections',()=>{const ids=AD_COLLECTIONS.flatMap(p=>p.styles);assert.equal(ids.length,12);assert.equal(new Set(ids).size,12);assert.equal(AD_COLLECTIONS.length,4);for(const id of ids)getMachineStyle(id);});
test('Paper order cycles every sheet without dropping or duplicating one',()=>{let order=[0,1,2];const seen=[];for(let i=0;i<30;i++){seen.push(order[0]);order=rotatePaperOrder(order);assert.deepEqual([...order].sort(),[0,1,2]);}assert.deepEqual(order,[0,1,2]);assert.deepEqual(seen.slice(0,3),[0,1,2]);assert(PAPER_STEP-PAPER_THICKNESS>.01);assert(PAPER_STEP-PAPER_THICKNESS/2>.027);});
test('Selector detents work across rotated and reversed camera projections',()=>{for(const [a,b]of [[{x:10,y:20},{x:110,y:20}],[{x:110,y:20},{x:10,y:120}],[{x:10,y:20},{x:10,y:120}]]){for(const count of [2,3])for(let i=0;i<count;i++){const t=i/(count-1);assert.equal(selectorIndex({x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t},a,b,count),i);}}assert.equal(selectorIndex({x:300,y:0},{x:0,y:0},{x:100,y:0},3),2);});
test('Tape drop hysteresis avoids door chatter at the target edge',()=>{const bounds={minX:0,maxX:200,minY:0,maxY:160};assert(insideTapeZone({x:100,y:80},bounds));assert(!insideTapeZone({x:210,y:80},bounds));assert(insideTapeZone({x:210,y:80},bounds,true));assert(!insideTapeZone({x:235,y:80},bounds,true));assert(!insideTapeZone({x:0,y:0},bounds));});
test('Standing feet, seated hips and desk objects meet their supports',()=>{const footBottom=.25-.23-.04/2;assert(Math.abs(footBottom)<1e-9);assert.equal(TABLE_TOP,.17);assert(Math.abs(.31+.24-(.50+.10/2))<1e-9);assert(Math.abs(.23+.24-(.32+.30/2))<1e-9);assert(Math.abs(-.115+.24-.125)<1e-9);assert(Math.abs(.266-.30*.64/2-TABLE_TOP)<1e-9);assert(Math.abs(.275-.21/2-TABLE_TOP)<1e-9);assert(.62-2.24*.38/2>TABLE_TOP);});
test('Top selectors seat on the cover and clear the handle and each other',()=>{const coverTop=7.03+.25/2,selectorBottom=7.20-.09/2;assert(Math.abs(coverTop-selectorBottom)<1e-9);const centers=[-4.15,-1.45,1.25];for(let i=1;i<centers.length;i++)assert(centers[i]-centers[i-1]>2.18+.40);assert(.78-.91/2>(-.15+.59/2)+.15);});
test('Parked incoming tape leaves the outgoing tape corridor clear',()=>{const incomingBottom=6.55-2.24/2,outgoingTop=3.59+2.24/2;assert(incomingBottom-outgoingTop>.70);assert(5.3-.30/2>1.66+3.1*Math.sin(OPEN_ANGLE)+.14);});
test('New editions include full wood, retro-future trim and monochrome shells',()=>{assert.equal(getMachineStyle('timber').caseWood,1);assert.equal(getMachineStyle('orbit').future,1);assert.equal(getMachineStyle('mono').colors.dark,'#141719');let order=[3,0,1,2];const seen=[];for(let i=0;i<4;i++){seen.push(order[0]);order=rotatePaperOrder(order);}assert.deepEqual(seen,[3,0,1,2]);assert.deepEqual(order,[3,0,1,2]);});
const prepared=await prepareAudio(new File([aiff(24,'NONE')],'fixture.aif',{type:'audio/aiff'}));assert(prepared.converted&&prepared.blob.type==='audio/wav');count++;console.log('PASS async local file preparation');
fs.writeFileSync(new URL('fixture-new.aif',import.meta.url),Buffer.from(aiff(24,'NONE')));fs.writeFileSync(new URL('fixture-new.au',import.meta.url),Buffer.from(au(3)));
console.log(`${count} domain checks passed. Browser visual/interaction verification is pending: current file URL is blocked by the browser tool policy.`);
