const fold=s=>String(s||'').normalize('NFKC').toLocaleLowerCase().trim();
export function findTapes(tracks,query){const words=fold(query).split(/\s+/).filter(Boolean);return tracks.filter(t=>words.every(w=>fold([t.title,t.artist,t.album,t.fileName].join(' ')).includes(w)));}
export function createMagnifier({getTracks,onLocate,onOpen,onClose,onSearch,getLocation}){
 const style=document.createElement('style');style.textContent=`
 #tape-inspector{position:fixed;left:max(18px,env(safe-area-inset-left));top:max(18px,env(safe-area-inset-top));width:350px;max-height:calc(100dvh - 36px);overflow:auto;background:#e8e3d5;color:#303d38;border:1px solid #939c8b;box-shadow:0 14px 45px #26342e30;border-radius:8px;padding:20px;font:14px/1.5 system-ui;z-index:10}#tape-inspector[hidden]{display:none}#tape-inspector *{box-sizing:border-box}#tape-inspector h2{font-size:18px;margin:0}#tape-inspector p{margin:8px 0;color:#667066}#tape-inspector button{font:inherit;color:inherit;background:#f6f2e8;border:1px solid #a6ad9c;border-radius:4px;padding:8px 12px;cursor:pointer;min-height:40px}#tape-inspector button:focus-visible,#tape-inspector input:focus-visible{outline:2px solid #af693e;outline-offset:2px}#tape-inspector header{display:flex;align-items:center;justify-content:space-between}#tape-inspector input{display:block;width:100%;padding:11px;border:1px solid #9ba493;background:#faf7ed;color:#303d38;font:inherit;margin:12px 0;border-radius:4px}#tape-inspector nav{display:flex;gap:8px}#tape-inspector [aria-pressed=true]{background:#344c43;color:#fff}#tape-results{display:grid;gap:6px;margin-top:10px}#tape-results button{text-align:left;overflow-wrap:anywhere}#tape-results small{display:block;color:#6a7369}#tape-detail{border-bottom:1px solid #b3b6a5;padding:12px 0}#tape-detail[hidden]{display:none}#tape-detail dl{display:grid;grid-template-columns:60px 1fr;margin:10px 0;gap:4px 8px}#tape-detail dt{color:#6a7369}#tape-detail dd{margin:0;overflow-wrap:anywhere}.inspection-tape{background:#c6caba;border:5px solid #88978b;border-radius:14px;padding:12px;box-shadow:inset 0 0 0 1px #edf0dc}.inspection-label{background:#d6c28c;display:flex;gap:10px;align-items:center;min-height:70px;padding:6px}.inspection-label img{width:64px;height:64px;object-fit:cover}.inspection-label strong{overflow-wrap:anywhere;line-height:1.3}.inspection-reels{display:flex;justify-content:space-around;align-items:center;margin:12px 0 2px;border-bottom:3px solid #443c32}.inspection-reels i{width:48px;height:48px;border:12px solid #665341;border-radius:50%;background:#ede8d8;box-shadow:inset 0 0 0 8px #a9b0a4}#tape-inspector .hint{font-size:12px}#tape-status{font-size:12px;margin:8px 0} @media(max-width:650px){#tape-inspector input{font-size:16px}#tape-inspector{left:8px;right:8px;top:auto;bottom:max(8px,env(safe-area-inset-bottom));width:auto;max-height:48dvh;padding:14px}.inspection-label{min-height:56px}.inspection-label img{width:52px;height:52px}.inspection-reels{display:none}}`;
 style.textContent+='#tape-inspector header{position:sticky;top:0;z-index:3;margin:0 -20px;padding:0 20px 8px;background:#e8e3d5;border-bottom:1px solid #b3b6a5}@media(max-width:650px){#tape-inspector header{margin:0 -14px;padding:0 14px 8px}}';
 document.head.append(style);const panel=document.createElement('section');panel.id='tape-inspector';panel.hidden=true;panel.setAttribute('role','region');panel.setAttribute('aria-label','放大镜 · 磁带检索');
 panel.innerHTML='<header><h2>放大镜 · 本地收藏</h2><button type="button" aria-label="关闭放大镜">×</button></header><p class="hint">点选柜中的磁带查看，或搜索歌曲、歌手、专辑。</p><input type="search" aria-label="检索磁带和专辑" placeholder="搜索歌曲、歌手、专辑…"><nav aria-label="检索类型"><button type="button" data-mode="songs" aria-pressed="true">磁带</button><button type="button" data-mode="albums" aria-pressed="false">专辑</button></nav><section id="tape-detail" hidden></section><p id="tape-status" role="status"></p><div id="tape-results"></div>';
 document.body.append(panel);const input=panel.querySelector('input'),results=panel.querySelector('#tape-results'),detail=panel.querySelector('#tape-detail'),status=panel.querySelector('#tape-status');let mode='songs',limit=30,selected=null,albumFilter=null;
 const el=(tag,text)=>{const e=document.createElement(tag);e.textContent=text;return e;};
 function show(){if(panel.hidden){panel.hidden=false;onOpen?.();}}
 function searchMode(){selected=null;detail.hidden=true;detail.replaceChildren();onSearch?.();}
 function close(){if(panel.hidden)return;panel.hidden=true;selected=null;detail.hidden=true;detail.replaceChildren();onClose?.();}
 panel.querySelector('header button').onclick=close;
 panel.addEventListener('keydown',e=>{e.stopPropagation();if(e.key==='Escape'){e.preventDefault();close();}});panel.addEventListener('keyup',e=>e.stopPropagation());
 input.addEventListener('input',()=>{searchMode();limit=30;albumFilter=null;render();});
 panel.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{searchMode();mode=b.dataset.mode;albumFilter=null;limit=30;panel.querySelectorAll('[data-mode]').forEach(t=>t.setAttribute('aria-pressed',String(t===b)));render();});
 function inspect(track,locate=true){if(!track)return;selected=track.id;show();detail.hidden=false;detail.replaceChildren();
 const tape=el('div','');tape.className='inspection-tape';tape.setAttribute('aria-label','磁带放大图');const label=el('div','');label.className='inspection-label';if(track.cover){const img=document.createElement('img');img.src=track.cover;img.alt=track.album+' 封面';img.onerror=()=>img.remove();label.append(img);}label.append(el('strong',track.title));tape.append(label);const reels=el('div','');reels.className='inspection-reels';reels.append(el('i',''),el('i',''));tape.append(reels);detail.append(tape);
 const dl=el('dl','');const seconds=Math.max(0,Math.floor(track.duration||0));for(const [k,v]of [['歌手',track.artist||'未知歌手'],['专辑',track.album||'本地磁带'],['时长',Math.floor(seconds/60)+':'+String(seconds%60).padStart(2,'0')],['格式',track.format||'未知'],['大小',((track.size||track.fileSize||0)/1048576).toFixed(1)+' MB'],['位置',getLocation(track)]])dl.append(el('dt',k),el('dd',v));detail.append(dl);
 const back=el('button','放下放大镜 · 返回搜索');back.type='button';back.onclick=()=>{searchMode();render();input.focus({preventScroll:true});};detail.append(back);
 const locateButton=el('button','定位这盘磁带');locateButton.type='button';locateButton.onclick=()=>onLocate(track);detail.append(locateButton);if(locate)onLocate(track);render();
 }
 let lastSignature='';
 function signature(){return JSON.stringify([mode,limit,input.value,albumFilter,getTracks().map(t=>[t.id,t.title,t.artist,t.album])]);}
 function render(){lastSignature=signature();const tracks=getTracks(),matches=findTapes(tracks,input.value).filter(t=>!albumFilter||JSON.stringify([t.artist,t.album])===albumFilter);results.replaceChildren();if(selected&&!tracks.some(t=>t.id===selected)){searchMode();}
 const albums=new Map();for(const t of matches){const key=JSON.stringify([t.artist,t.album]);if(!albums.has(key))albums.set(key,[]);albums.get(key).push(t);}const rows=mode==='albums'?[...albums.values()]:matches;
 status.textContent=tracks.length?(rows.length?`${rows.length} ${mode==='albums'?'张专辑':'盘磁带'}${rows.length>limit?' · 先显示 '+limit+' 项':''}`:'没有匹配结果，请换个关键词。'):'还没有收藏，可从专辑柜或刻录机导入音乐。';
 for(const row of rows.slice(0,limit)){const t=mode==='albums'?row[0]:row,b=el('button',mode==='albums'?(t.album||'本地磁带'):t.title);b.type='button';b.append(el('small',mode==='albums'?`${t.artist} · ${row.length} 首`: `${t.artist} · ${t.album}`));b.onclick=()=>{if(mode==='albums'){searchMode();mode='songs';albumFilter=JSON.stringify([t.artist,t.album]);input.value='';panel.querySelectorAll('[data-mode]').forEach(x=>x.setAttribute('aria-pressed',String(x.dataset.mode===mode)));render();}else inspect(t);};results.append(b);}
 if(rows.length>limit){const more=el('button','显示更多');more.onclick=()=>{limit+=30;render();};results.append(more);}}
 return {get active(){return !panel.hidden;},open(){show();searchMode();render();input.focus({preventScroll:true});},close,inspect,lower(){onSearch?.('physical');},relocate(){const t=getTracks().find(t=>t.id===selected);if(t)onLocate(t);},refresh(){if(!panel.hidden&&signature()!==lastSignature)render();}};
}
