const fold=s=>String(s||'').normalize('NFKC').toLocaleLowerCase().trim();
export function findTapes(tracks,query){const words=fold(query).split(/\s+/).filter(Boolean);return tracks.filter(t=>words.every(w=>fold([t.title,t.artist,t.album,t.fileName].join(' ')).includes(w)));}
export function createMagnifier({playbackLists,getTracks,onLocate,onOpen,onClose,onSearch,getLocation,onOrganize,onDelete,onDownload,onDownloadOne}){
 const style=document.createElement('style');style.textContent=`
 #tape-inspector{position:fixed;left:max(18px,env(safe-area-inset-left));top:max(18px,env(safe-area-inset-top));width:350px;max-height:calc(100dvh - 36px);overflow:auto;background:#e8e3d5;color:#303d38;border:1px solid #939c8b;box-shadow:0 14px 45px #26342e30;border-radius:8px;padding:20px;font:14px/1.5 system-ui;z-index:10}#tape-inspector[hidden]{display:none}#tape-inspector *{box-sizing:border-box}#tape-inspector h2{font-size:18px;margin:0}#tape-inspector p{margin:8px 0;color:#667066}#tape-inspector button{font:inherit;color:inherit;background:#f6f2e8;border:1px solid #a6ad9c;border-radius:4px;padding:8px 12px;cursor:pointer;min-height:40px}#tape-inspector button:focus-visible,#tape-inspector input:focus-visible{outline:2px solid #af693e;outline-offset:2px}#tape-inspector header{display:flex;align-items:center;justify-content:space-between}#tape-inspector input{display:block;width:100%;padding:11px;border:1px solid #9ba493;background:#faf7ed;color:#303d38;font:inherit;margin:12px 0;border-radius:4px}#tape-inspector nav{display:flex;gap:8px}#tape-inspector [aria-pressed=true]{background:#344c43;color:#fff}#tape-results{display:grid;gap:6px;margin-top:10px}#tape-results button{text-align:left;overflow-wrap:anywhere}#tape-results small{display:block;color:#6a7369}#tape-detail{border-bottom:1px solid #b3b6a5;padding:12px 0}#tape-detail[hidden]{display:none}#tape-detail dl{display:grid;grid-template-columns:60px 1fr;margin:10px 0;gap:4px 8px}#tape-detail dt{color:#6a7369}#tape-detail dd{margin:0;overflow-wrap:anywhere}.inspection-tape{background:#c6caba;border:5px solid #88978b;border-radius:14px;padding:12px;box-shadow:inset 0 0 0 1px #edf0dc}.inspection-label{background:#d6c28c;display:flex;gap:10px;align-items:center;min-height:70px;padding:6px}.inspection-label img{width:64px;height:64px;object-fit:cover}.inspection-label strong{overflow-wrap:anywhere;line-height:1.3}.inspection-reels{display:flex;justify-content:space-around;align-items:center;margin:12px 0 2px;border-bottom:3px solid #443c32}.inspection-reels i{width:48px;height:48px;border:12px solid #665341;border-radius:50%;background:#ede8d8;box-shadow:inset 0 0 0 8px #a9b0a4}#tape-inspector .hint{font-size:12px}#tape-status{font-size:12px;margin:8px 0} @media(max-width:650px){#tape-inspector input{font-size:16px}#tape-inspector{left:8px;right:8px;top:auto;bottom:max(8px,env(safe-area-inset-bottom));width:auto;max-height:48dvh;padding:14px}.inspection-label{min-height:56px}.inspection-label img{width:52px;height:52px}.inspection-reels{display:none}}`;
 style.textContent+='#tape-inspector header{position:sticky;top:0;z-index:3;margin:0 -20px;padding:0 20px 8px;background:#e8e3d5;border-bottom:1px solid #b3b6a5}@media(max-width:650px){#tape-inspector header{margin:0 -14px;padding:0 14px 8px}}';
 style.textContent+=`#tape-inspector .tape-row{display:grid;grid-template-columns:minmax(0,1fr) auto auto;gap:6px;align-items:center}#tape-inspector .tape-row[data-selectable]{grid-template-columns:22px minmax(0,1fr) auto auto}#tape-inspector .tape-row input{width:20px;height:20px;margin:0;accent-color:#344c43;cursor:pointer}#tape-inspector .row-delete{font-size:12px;padding:8px;min-width:44px}#tape-inspector [hidden]{display:none}#tape-inspector .manage-tools{border-top:1px solid #b3b6a5;padding-top:12px;margin-top:12px}#tape-inspector .manage-tools select{font:inherit;min-height:40px;max-width:100%;color:inherit;background:#faf7ed;border:1px solid #9ba493;border-radius:4px;padding:6px}#tape-inspector .tool-row{display:flex;gap:6px;flex-wrap:wrap;align-items:center;margin-top:8px}#tape-inspector .delete-confirm{margin-top:10px;padding-top:10px;border-top:1px solid #b3b6a5}#tape-inspector button:disabled{opacity:.5;cursor:wait}#tape-inspector .manage-notice{font-size:12px;overflow-wrap:anywhere}#tape-inspector .danger{color:#863e2a}`;
 style.textContent+=`#tape-inspector{width:430px;padding:18px}#tape-inspector header{margin:0 -18px;padding:0 18px 10px}#tape-inspector nav{gap:0;border-bottom:1px solid #b3b6a5;margin-bottom:12px}#tape-inspector nav button{flex:1;border:0;border-radius:0;background:transparent}#tape-inspector nav [aria-pressed=true]{background:transparent;color:#344c43;box-shadow:inset 0 -3px #344c43;font-weight:600}#tape-inspector .search-filter{display:flex;align-items:center;gap:8px;margin:8px 0}#tape-inspector .search-filter select{flex:1;min-width:0;padding:7px;border:1px solid #a6ad9c;background:#f6f2e8;color:inherit;border-radius:4px;font:inherit}#tape-inspector .manage-tools{border:0;margin:0;padding:0}#tape-inspector [data-management]{padding:10px;margin-top:8px;border:1px solid #b3b6a5;border-radius:5px}#tape-inspector .tape-row{grid-template-columns:minmax(0,1fr) auto;border-bottom:1px solid #bdc0b2;padding:6px 0}#tape-inspector .tape-row[data-selectable]{grid-template-columns:22px minmax(0,1fr) auto auto}#tape-inspector .tape-row[data-managing]{grid-template-columns:22px minmax(0,1fr) auto auto auto}#tape-inspector .song-main{border:0;background:transparent;padding:6px;display:flex;gap:10px;align-items:center;min-width:0}#tape-inspector .song-main img,#tape-inspector .cover-placeholder{width:44px;height:44px;object-fit:cover;flex:none;border-radius:3px;background:#c4c8b7;display:grid;place-items:center;color:#6a7369}#tape-inspector .song-info{min-width:0}#tape-inspector .song-info strong{display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden;font-weight:600;line-height:1.35}#tape-inspector .song-info small{font-size:12px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;max-width:255px}#tape-inspector .row-list{background:transparent;font-size:12px;padding:5px 7px}#tape-inspector .download-toolbar{display:flex;gap:8px;flex-wrap:wrap}#tape-inspector .download-toolbar button{flex:1}#tape-inspector .manage-notice:empty{display:none}#tape-detail button{margin:4px 4px 4px 0}@media(max-width:650px){#tape-inspector{width:auto;padding:14px}#tape-inspector header{margin:0 -14px;padding:0 14px 8px}}`;
 document.head.append(style);const panel=document.createElement('section');panel.id='tape-inspector';panel.hidden=true;panel.setAttribute('role','region');panel.setAttribute('aria-label','放大镜 · 磁带检索');
 panel.innerHTML='<header><h2>放大镜 · 本地收藏</h2><button type="button" aria-label="关闭放大镜">×</button></header><p class="hint">点选柜中的磁带查看，或搜索歌曲、歌手、专辑。</p><input type="search" aria-label="检索磁带和专辑" placeholder="搜索歌曲、歌手、专辑…"><nav aria-label="检索类型"><button type="button" data-mode="songs" aria-pressed="true">磁带</button><button type="button" data-mode="albums" aria-pressed="false">专辑</button><button type="button" data-mode="playlists" aria-pressed="false">播放列表</button></nav><section data-playback-lists hidden></section><section id="tape-detail" hidden></section><p id="tape-status" role="status"></p><div id="tape-results"></div>';
 document.body.append(panel);const input=panel.querySelector('input'),results=panel.querySelector('#tape-results'),detail=panel.querySelector('#tape-detail'),status=panel.querySelector('#tape-status');let mode='songs',limit=30,selected=null,albumFilter=null,managing=false,operation=false,confirmIds=[];const checked=new Set();
 const el=(tag,text)=>{const e=document.createElement(tag);e.textContent=text;return e;};
 const tools=el('section','');tools.className='manage-tools';tools.innerHTML='<button type="button" data-manage aria-expanded="false">整理磁带</button><div data-management hidden><p class="hint">重排柜内位置，保留正在播放的磁带和播放顺序。</p><label>柜内排列 <select aria-label="柜内排列方式"><option value="album">按专辑</option><option value="artist">按歌手</option><option value="title">按曲名</option><option value="oldest">先导入在前</option><option value="newest">新导入在前</option></select></label><button type="button" data-sort>整理柜内位置</button><div class="tool-row"><button type="button" data-select-all>全选当前结果</button><button type="button" data-select-none>取消勾选</button><button type="button" class="danger" data-delete-checked>删除已选</button></div><p data-selection class="hint"></p></div><p class="manage-notice" role="status" data-notice></p><div class="delete-confirm" hidden><p data-confirm-text></p><div class="tool-row"><button type="button" class="danger" data-confirm-delete></button><button type="button" data-cancel-delete>取消</button></div></div>';
 panel.insertBefore(tools,status);const manageButton=tools.querySelector('[data-manage]'),manageBody=tools.querySelector('[data-management]'),confirm=tools.querySelector('.delete-confirm'),notice=tools.querySelector('[data-notice]'),selection=tools.querySelector('[data-selection]'),deleteChecked=tools.querySelector('[data-delete-checked]');
 const filters=el('div','');filters.className='search-filter';filters.innerHTML='<select data-format-filter aria-label="筛选收藏"><option value="all">全部收藏</option><option value="recorded">已刻录 MP3</option></select><select data-display-sort aria-label="搜索结果排序"><option value="cabinet">柜内顺序</option><option value="title">曲名</option><option value="artist">歌手</option><option value="newest">最近导入</option></select>';panel.insertBefore(filters,tools);const formatFilter=filters.querySelector('[data-format-filter]'),displaySort=filters.querySelector('[data-display-sort]');
 const download=el('button','下载 MP3');download.type='button';download.dataset.downloadMp3='';const toolbar=el('div','');toolbar.className='download-toolbar';tools.prepend(toolbar);toolbar.append(manageButton,download);
 const eligible=t=>t.recorded&&t.format==='MP3'&&!!t.audioBlob;
 for(const f of [formatFilter,displaySort])f.onchange=()=>{searchMode();resetSelection();limit=30;render();};
 download.onclick=async()=>{if(operation)return;const batch=matched().filter(t=>eligible(t)&&checked.has(t.id));if(!batch.length)return;operation=true;onSearch?.('manage');syncTools();try{const n=await onDownload(batch.map(t=>t.id),(done,total)=>notice.textContent='正在打包 '+done+' / '+total+' 首 MP3…');notice.textContent='已下载 '+n+' 首 MP3；解压后按歌手和专辑存放。';}catch(e){notice.textContent=e.message||'下载未完成，请重试。';}finally{operation=false;render();}};
 const listEditor=playbackLists?.mount(panel.querySelector('[data-playback-lists]'));
 const matched=()=>{const rows=findTapes(getTracks(),input.value).filter(t=>(!albumFilter||JSON.stringify([t.artist,t.album])===albumFilter)&&(formatFilter.value!=='recorded'||eligible(t)));if(displaySort.value==='newest')rows.sort((a,b)=>(b.createdAt||0)-(a.createdAt||0));else if(displaySort.value!=='cabinet')rows.sort((a,b)=>String(a[displaySort.value]||'').localeCompare(String(b[displaySort.value]||''),'zh'));return rows;};
 function clearConfirmation(){confirmIds=[];confirm.hidden=true;}
 function resetSelection(){checked.clear();clearConfirmation();}
 function syncTools(){const count=matched().filter(t=>eligible(t)&&checked.has(t.id)).length;download.textContent='下载已选 MP3'+'（'+count+'）';download.disabled=operation||!count;selection.textContent='已选 '+checked.size+' 盘磁带';deleteChecked.textContent='删除已选'+(checked.size?'（'+checked.size+'）':'');manageBody.hidden=!managing;manageButton.textContent=managing?'完成选择':'选择 / 整理';manageButton.setAttribute('aria-expanded',String(managing));for(const e of panel.querySelectorAll('button,input,select'))if(e!==panel.querySelector('header button'))e.disabled=operation;download.disabled=operation||!count;deleteChecked.disabled=operation||!checked.size;tools.querySelector('[data-sort]').disabled=operation||!getTracks().length;}
 function askDelete(ids){if(operation)return;const unique=new Set(ids),tracks=getTracks().filter(t=>unique.has(t.id));if(!tracks.length)return;onSearch?.('manage');confirmIds=tracks.map(t=>t.id);confirm.hidden=false;
 const names=tracks.slice(0,3).map(t=>'“'+t.title+'”').join('、')+(tracks.length>3?'等':''),inMachine=tracks.some(t=>getLocation(t)==='磁带机内');tools.querySelector('[data-confirm-text]').textContent='从本地收藏删除 '+tracks.length+' 盘：'+names+'？'+(inMachine?'机内磁带会先退出。':'')+'原始音乐文件和已导出的 MP3 会保留。';tools.querySelector('[data-confirm-delete]').textContent='确认删除 '+tracks.length+' 盘';confirm.scrollIntoView({block:'nearest',behavior:'smooth'});}
 manageButton.onclick=()=>{if(operation)return;managing=!managing;searchMode();resetSelection();notice.textContent='';render();};
 tools.querySelector('[data-select-all]').onclick=()=>{clearConfirmation();for(const t of matched())checked.add(t.id);render();};
 tools.querySelector('[data-select-none]').onclick=()=>{resetSelection();render();};deleteChecked.onclick=()=>askDelete([...checked]);tools.querySelector('[data-cancel-delete]').onclick=clearConfirmation;
 tools.querySelector('[data-confirm-delete]').onclick=async()=>{if(operation||!confirmIds.length)return;const ids=[...confirmIds];operation=true;notice.textContent='正在收好磁带并删除…';syncTools();try{const count=await onDelete(ids);resetSelection();searchMode();notice.textContent='已删除 '+count+' 盘磁带。';}catch(e){notice.textContent=e.message||'删除未完成。';}finally{operation=false;render();}};
 tools.querySelector('[data-sort]').onclick=async()=>{if(operation)return;operation=true;clearConfirmation();onSearch?.('manage');notice.textContent='正在整理柜内位置…';syncTools();try{const count=await onOrganize(tools.querySelector('select').value);notice.textContent='已整理 '+count+' 盘磁带，播放顺序保持原样。';}catch(e){notice.textContent=e.message||'整理未完成。';}finally{operation=false;render();}};
 function show(){if(panel.hidden){panel.hidden=false;onOpen?.();}}
 function searchMode(){selected=null;detail.hidden=true;detail.replaceChildren();onSearch?.();}
 function close(){if(panel.hidden)return;managing=false;resetSelection();syncTools();panel.hidden=true;selected=null;detail.hidden=true;detail.replaceChildren();onClose?.();}
 panel.querySelector('header button').onclick=close;
 panel.addEventListener('keydown',e=>{e.stopPropagation();if(e.key==='Escape'){e.preventDefault();close();}});panel.addEventListener('keyup',e=>e.stopPropagation());
 input.addEventListener('input',()=>{searchMode();resetSelection();notice.textContent='';limit=30;albumFilter=null;render();});
 panel.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{searchMode();resetSelection();notice.textContent='';mode=b.dataset.mode;albumFilter=null;limit=30;panel.querySelectorAll('[data-mode]').forEach(t=>t.setAttribute('aria-pressed',String(t===b)));render();});
 function inspect(track,locate=true){if(!track)return;selected=track.id;show();detail.hidden=false;detail.replaceChildren();
 const tape=el('div','');tape.className='inspection-tape';tape.setAttribute('aria-label','磁带放大图');const label=el('div','');label.className='inspection-label';if(track.cover){const img=document.createElement('img');img.src=track.cover;img.alt=track.album+' 封面';img.onerror=()=>img.remove();label.append(img);}label.append(el('strong',track.title));tape.append(label);const reels=el('div','');reels.className='inspection-reels';reels.append(el('i',''),el('i',''));tape.append(reels);detail.append(tape);
 const dl=el('dl','');const seconds=Math.max(0,Math.floor(track.duration||0));for(const [k,v]of [['歌手',track.artist||'未知歌手'],['专辑',track.album||'本地磁带'],['时长',Math.floor(seconds/60)+':'+String(seconds%60).padStart(2,'0')],['格式',track.format||'未知'],['大小',((track.size||track.fileSize||0)/1048576).toFixed(1)+' MB'],['位置',getLocation(track)],['歌词',track.lyrics?.cues?.length?(track.lyrics.timed?'同步歌词':'文本歌词')+(track.lyricsOrigin==='online'?' · LRCLIB':track.lyricsOrigin==='lrc'?' · 本地 LRC':' · 内嵌'):track.lyricStatus==='instrumental'?'纯音乐':track.lyricStatus==='missing-metadata'?'缺少曲名或歌手信息':track.lyricStatus==='not-found'?'未找到匹配歌词':'暂无歌词']])dl.append(el('dt',k),el('dd',v));detail.append(dl);
 const back=el('button','放下放大镜 · 返回搜索');back.type='button';back.onclick=()=>{searchMode();render();input.focus({preventScroll:true});};detail.append(back);
 const locateButton=el('button','定位这盘磁带');locateButton.type='button';locateButton.onclick=()=>onLocate(track);detail.append(locateButton);const addList=el('button','加入播放列表');addList.onclick=()=>{try{playbackLists.add(playbackLists.local(track));notice.textContent='已加入 '+playbackLists.selected().name;}catch(e){notice.textContent=e.message;}};detail.append(addList);const remove=el('button','删除这盘磁带');remove.type='button';remove.className='danger';remove.onclick=()=>askDelete([track.id]);detail.append(remove);if(locate)onLocate(track);render();
 }
 let lastSignature='';
 function signature(){return JSON.stringify([mode,limit,input.value,albumFilter,formatFilter.value,displaySort.value,getTracks().map(t=>[t.id,t.title,t.artist,t.album,t.cabinetSlot,getLocation(t)])]);}
 function render(){lastSignature=signature();const lists=mode==='playlists';panel.querySelector('[data-playback-lists]').hidden=!lists;input.hidden=lists;filters.hidden=lists;tools.hidden=lists;results.hidden=lists;status.hidden=lists;if(lists){listEditor?.refresh();return;}const tracks=getTracks(),matches=matched();results.replaceChildren();for(const id of checked)if(!tracks.some(t=>t.id===id))checked.delete(id);if(selected&&!tracks.some(t=>t.id===selected)){searchMode();}
 const albums=new Map();for(const t of matches){const key=JSON.stringify([t.artist,t.album]);if(!albums.has(key))albums.set(key,[]);albums.get(key).push(t);}const rows=mode==='albums'?[...albums.values()]:matches;
 status.textContent=tracks.length?(rows.length?`${rows.length} ${mode==='albums'?'张专辑':'盘磁带'}${rows.length>limit?' · 先显示 '+limit+' 项':''}`:'没有匹配结果，请换个关键词。'):'还没有收藏，可从专辑柜或刻录机导入音乐。';
 for(const row of rows.slice(0,limit)){const t=mode==='albums'?row[0]:row,b=el('button','');b.type='button';b.className='song-main';if(t.cover){const image=document.createElement('img');image.src=t.cover;image.alt='';image.loading='lazy';image.onerror=()=>image.remove();b.append(image);}else{const icon=el('span','♫');icon.className='cover-placeholder';b.append(icon);}const info=el('span','');info.className='song-info';info.append(el('strong',mode==='albums'?(t.album||'本地磁带'):t.title));info.append(el('small',mode==='albums'?`${t.artist} · ${row.length} 首`: `${t.artist} · ${t.album}`));const sec=Math.floor(t.duration||0);info.append(el('small',mode==='albums'?'专辑':`${Math.floor(sec/60)}:${String(sec%60).padStart(2,'0')} · ${t.format||'音频'}${eligible(t)?' · 已刻录':''}`));b.append(info);b.onclick=()=>{if(mode==='albums'){searchMode();resetSelection();mode='songs';albumFilter=JSON.stringify([t.artist,t.album]);input.value='';panel.querySelectorAll('[data-mode]').forEach(x=>x.setAttribute('aria-pressed',String(x.dataset.mode===mode)));render();}else inspect(t);};const line=el('div','');line.className='tape-row';const ids=mode==='albums'?row.map(t=>t.id):[t.id];
 if(managing||mode==='songs'&&eligible(t)){line.dataset.selectable='';const check=document.createElement('input');check.type='checkbox';check.setAttribute('aria-label','选择'+(mode==='albums'?'专辑：'+t.album:'磁带：'+t.title));check.checked=ids.every(id=>checked.has(id));check.indeterminate=!check.checked&&ids.some(id=>checked.has(id));check.onchange=()=>{clearConfirmation();for(const id of ids)check.checked?checked.add(id):checked.delete(id);syncTools();};line.append(check);}
 line.append(b);if(mode==='songs'&&eligible(t)){const single=el('button','下载');single.type='button';single.setAttribute('aria-label','下载 MP3：'+t.title);single.onclick=()=>{try{onDownloadOne(t.id);notice.textContent='已下载 '+t.title;}catch(e){notice.textContent=e.message;}};line.append(single);}const addList=el('button','＋列表');addList.className='row-list';addList.setAttribute('aria-label','加入播放列表：'+t.title);addList.onclick=()=>{try{for(const item of mode==='albums'?row:[t])playbackLists.add(playbackLists.local(item));notice.textContent='已加入 '+playbackLists.selected().name;}catch(e){notice.textContent=e.message;}};line.append(addList);const remove=el('button','删除');remove.type='button';remove.className='row-delete danger';remove.setAttribute('aria-label',mode==='albums'?'删除专辑中的磁带：'+t.album+' · '+t.artist:'删除磁带：'+t.title);remove.onclick=()=>askDelete(ids);if(managing){line.dataset.managing='';line.append(remove)};results.append(line);}
 syncTools();if(rows.length>limit){const more=el('button','显示更多');more.onclick=()=>{limit+=30;render();};results.append(more);}}
 return {get active(){return !panel.hidden;},open(){show();searchMode();resetSelection();render();input.focus({preventScroll:true});},close,inspect,lower(){onSearch?.('physical');},relocate(){const t=getTracks().find(t=>t.id===selected);if(t)onLocate(t);},refresh(){if(!panel.hidden&&signature()!==lastSignature)render();}};
}
