import {parseLyrics,MAX_LYRIC_BYTES} from './lyric-data.js';
export function safeOnlineUrl(value){try{const u=new URL(value);return u.protocol==='https:'||u.protocol==='http:'&&['localhost','127.0.0.1','[::1]'].includes(u.hostname)?u.href:'';}catch{return '';}}
const short=(v,n=240)=>String(v||'').slice(0,n),key=t=>t.provider+':'+t.id;
export function onlineRecord(t){return {id:short(t.id,100),provider:t.provider,title:short(t.title),artist:short(t.artist),album:short(t.album),duration:Math.max(0,Number(t.duration)||0),platform:short(t.platform,30),pageUrl:safeOnlineUrl(t.pageUrl),downloadable:!!t.downloadable};}
export function audiusTrack(t){if(!t?.id||!t.title||t.is_streamable===false||t.is_gated||t.access?.stream===false)return null;return {...onlineRecord({id:t.id,provider:'audius',title:t.title,artist:t.user?.name||t.user?.handle||'UNKNOWN ARTIST',album:t.album_backlink?.album_name||'',duration:t.duration,pageUrl:t.permalink?'https://audius.co'+t.permalink:'',downloadable:t.is_downloadable===true&&t.access?.download!==false}),coverUrl:safeOnlineUrl(t.artwork?.['150x150']),streamUrl:'https://api.audius.co/v1/tracks/'+encodeURIComponent(t.id)+'/stream?app_name=CassetteWorld'};}
export function metingTrack(t,platform,index){if(!t?.name&&!t?.title)return null;let linkId='';try{linkId=new URL(t.url).searchParams.get('id')||'';}catch{}const id=t.id||t.url_id||linkId||t.url||index;const rawLyrics=t.lyrics||t.lyric||'';return {...onlineRecord({id,provider:'meting',platform,title:t.name||t.title,artist:Array.isArray(t.artist)?t.artist.join(' / '):t.artist,album:t.album,duration:t.duration||Number(t.dt||0)/1000,downloadable:t.downloadable===true,pageUrl:t.pageUrl}),streamUrl:safeOnlineUrl(t.url),lyricUrl:safeOnlineUrl(t.lrc),lyricId:t.lyric_id||t.id,lyrics:typeof rawLyrics==='string'&&rawLyrics.length<=MAX_LYRIC_BYTES?parseLyrics(rawLyrics):null};}
export function createOnlineMusic({fetcher=(...a)=>fetch(...a),timeoutMs=12000}={}){
 async function request(url,signal,asText=false,max=1024*1024){const controller=new AbortController(),abort=()=>controller.abort();signal?.addEventListener('abort',abort,{once:true});if(signal?.aborted)controller.abort();const timer=setTimeout(abort,timeoutMs);try{const r=await fetcher(url,{signal:controller.signal,credentials:'omit',referrerPolicy:'no-referrer'});if(!r.ok)throw Error(r.status===429?'请求较多，请稍后重试。':'连接失败，请重试。');const reader=r.body?.getReader();let text;if(reader){let n=0;const chunks=[];while(true){const {done,value}=await reader.read();if(done)break;n+=value.byteLength;if(n>max){await reader.cancel();throw Error('返回内容过大。');}chunks.push(value);}const bytes=new Uint8Array(n);let p=0;for(const c of chunks){bytes.set(c,p);p+=c.length;}text=new TextDecoder().decode(bytes);}else{text=await r.text();if(text.length>max)throw Error('返回内容过大。');}return asText?text:JSON.parse(text);}catch(e){if(e.name==='AbortError')throw Error(signal?.aborted?'已取消查找。':'连接超时，请重试。');throw e;}finally{clearTimeout(timer);signal?.removeEventListener('abort',abort);}}
 function metingUrl(config,type,id){const endpoint=safeOnlineUrl(config.endpoint);if(!endpoint)throw Error('请在螺丝盒设置中填写可用的 Meting 接口地址。');const u=new URL(endpoint);u.searchParams.set('server',config.platform||'netease');u.searchParams.set('type',type);u.searchParams.set('id',id);return u.href;}
 return {
  async search(query,config,signal){const q=short(query).trim();if(!q)return [];if(config.provider==='meting'){const data=await request(metingUrl(config,'search',q),signal);const rows=Array.isArray(data)?data:data.data||data.result?.songs||[];if(!Array.isArray(rows))throw Error('接口未返回歌曲列表。');return rows.slice(0,40).map((t,i)=>metingTrack(t,config.platform,i)).filter(Boolean);}const url=new URL('https://api.audius.co/v1/tracks/search');url.searchParams.set('query',q);url.searchParams.set('limit','40');url.searchParams.set('app_name','CassetteWorld');const data=await request(url.href,signal);return (data.data||[]).map(audiusTrack).filter(Boolean).slice(0,40);},
  async resolve(track,config,signal){if(track.provider==='audius'){const data=await request('https://api.audius.co/v1/tracks/'+encodeURIComponent(track.id)+'?app_name=CassetteWorld',signal);const row=audiusTrack(Array.isArray(data.data)?data.data[0]:data.data);if(!row)throw Error('这首歌暂时无法在线播放。');return row;}let t={...track};if(!safeOnlineUrl(t.streamUrl)){const data=await request(metingUrl({...config,platform:t.platform},'song',t.id),signal);const row=Array.isArray(data)?data[0]:data.data?.[0]||data;const fresh=metingTrack(row,t.platform,0);if(fresh)t={...t,...fresh};}if(!safeOnlineUrl(t.streamUrl))throw Error('接口没有提供可播放地址。');if(!t.lyrics?.cues?.length&&t.lyricUrl){try{t.lyrics=parseLyrics(await request(t.lyricUrl,signal,true,MAX_LYRIC_BYTES));}catch{}}return t;},
  async download(track,signal,onProgress){if(!track.downloadable)throw Error('这首歌的来源未开放下载，点歌卡仍可在线播放。');const url=track.provider==='audius'?'https://api.audius.co/v1/tracks/'+encodeURIComponent(track.id)+'/download?app_name=CassetteWorld':safeOnlineUrl(track.streamUrl);if(!url)throw Error('没有下载地址。');const controller=new AbortController(),abort=()=>controller.abort();signal?.addEventListener('abort',abort,{once:true});if(signal?.aborted)abort();const timer=setTimeout(abort,60000);try{const r=await fetcher(url,{signal:controller.signal,credentials:'omit',referrerPolicy:'no-referrer'});if(!r.ok)throw Error('下载未完成，点歌卡已保留。');const total=Number(r.headers.get('Content-Length'))||0;if(total>64*1024*1024)throw Error('音频超过 64 MB。');const reader=r.body?.getReader(),chunks=[];let size=0;if(reader){while(true){const {done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>64*1024*1024){await reader.cancel();throw Error('音频超过 64 MB。');}chunks.push(value);onProgress?.(total?size/total:null);}}else{const blob=await r.blob();if(blob.size>64*1024*1024)throw Error('音频超过 64 MB。');chunks.push(blob);}return new Blob(chunks,{type:r.headers.get('Content-Type')?.split(';')[0]||'audio/mpeg'});}finally{clearTimeout(timer);signal?.removeEventListener('abort',abort);}},
  key
 };
}
