import {onlineRecord} from './online-music.js';
const key=e=>e.kind==='local'?'local:'+e.id:'online:'+e.track.provider+':'+e.track.id;
export function createPlaybackLists({persist,playEntry,getCatalog}){
 const state={id:'playback-lists',selectedId:null,activeId:null,lists:[],cursor:0,revision:0};const watchers=new Set();let saveJob,saving=false,dirty=false,playing=false;
 const selected=()=>state.lists.find(l=>l.id===state.selectedId),active=()=>state.lists.find(l=>l.id===state.activeId);
 const emit=()=>{state.revision++;for(const fn of watchers)fn();};
 async function save(){if(saving){dirty=true;return;}saving=true;try{await persist(JSON.parse(JSON.stringify(state)));}catch{for(const fn of watchers)fn('播放列表未能保存，请重试');}finally{saving=false;if(dirty){dirty=false;save();}}}
 function changed(){emit();clearTimeout(saveJob);saveJob=setTimeout(save,180);}
 function create(name='我的播放列表'){if(state.lists.length>=30)throw Error('最多保存 30 个播放列表');const l={id:crypto.randomUUID(),name:String(name).trim().slice(0,60)||'我的播放列表',entries:[]};state.lists.push(l);state.selectedId=l.id;changed();return l;}
 function ensure(){return selected()||create();}
 function add(entry){const l=ensure();if(l.entries.some(e=>key(e)===key(entry)))return false;if(l.entries.length>=300)throw Error('每个列表最多 300 首');l.entries.push(entry);changed();return true;}
 async function start(index=0){const l=selected();if(!l?.entries.length)throw Error('先加入歌曲');state.activeId=l.id;state.cursor=Math.max(0,Math.min(index,l.entries.length-1));changed();return run(l.entries[state.cursor]);}
 async function run(entry){if(playing)return;playing=true;try{await playEntry(entry);}finally{playing=false;emit();}}
 async function advance(direction,currentKey,{automatic=false,repeat=false,shuffle=false}={}){const l=active();if(!l?.entries.length)return false;let at=l.entries.findIndex(e=>key(e)===currentKey);if(at<0)at=state.cursor-direction;let n=at+direction;if(shuffle&&l.entries.length>1){do{n=Math.floor(Math.random()*l.entries.length);}while(n===at);}if(automatic&&!repeat&&!shuffle&&n>=l.entries.length)return true;n=(n+l.entries.length)%l.entries.length;state.cursor=n;changed();await run(l.entries[n]);return true;}
 function remove(i){const l=selected();if(!l)return;l.entries.splice(i,1);if(l.id===state.activeId&&i<state.cursor)state.cursor--;changed();}
 function move(i,d){const l=selected(),n=i+d;if(!l||n<0||n>=l.entries.length)return;[l.entries[i],l.entries[n]]=[l.entries[n],l.entries[i]];changed();}
 function replace(i,entry){const l=selected();if(!l)return;l.entries[i]=entry;changed();}
 function prune(ids){for(const l of state.lists)l.entries=l.entries.filter(e=>e.kind!=='local'||!ids.has(e.id));changed();}
 function restore(data){if(!data)return;state.lists=(data.lists||[]).slice(0,30).filter(l=>l.id&&Array.isArray(l.entries)).map(l=>({id:String(l.id),name:String(l.name||'播放列表').slice(0,60),entries:l.entries.slice(0,300).filter(e=>e.kind==='local'&&e.id||e.kind==='online'&&e.track?.id&&e.track?.provider)}));state.selectedId=data.selectedId;state.activeId=state.lists.some(l=>l.id===data.activeId)?data.activeId:null;state.cursor=Math.max(0,data.cursor||0);emit();}
 const local=t=>({kind:'local',id:t.id,title:t.title,artist:t.artist});const online=(t,config)=>({kind:'online',track:onlineRecord(t),config:{...config},title:t.title,artist:t.artist});
 function mount(host,{compact=false}={}){
  host.classList.add('playback-list-editor');host.dataset.compact=String(compact);let replaceIndex=null,focusIndex=0;
  host.innerHTML='<div class="pl-tools"><select data-pl-select aria-label="选择播放列表"></select><button data-pl-new>新建</button><button data-pl-delete>删除列表</button></div><div class="pl-tools"><input data-pl-name aria-label="播放列表名称" maxlength="60"><button data-pl-rename>改名</button></div><div class="pl-tools"><button data-pl-play>播放列表</button><button data-pl-off>按柜内顺序</button></div><p data-pl-status role="status"></p><div data-pl-rows></div><div class="pl-tools"><select data-pl-catalog aria-label="选择加入或替换的歌曲"></select><button data-pl-add>加入</button><button data-pl-cancel hidden>取消替换</button></div>';
  const q=s=>host.querySelector(s),notice=q('[data-pl-status]');let catalog=[];
  const attempt=async fn=>{try{await fn();}catch(e){notice.textContent=e.message||'操作未完成';}};
  function draw(message){const l=selected(),listSelect=q('[data-pl-select]');listSelect.replaceChildren();for(const item of state.lists){const opt=document.createElement('option');opt.value=item.id;opt.textContent=item.name;opt.selected=item.id===state.selectedId;listSelect.append(opt);}if(document.activeElement!==q('[data-pl-name]'))q('[data-pl-name]').value=l?.name||'';
   notice.textContent=message||(state.activeId?'播放顺序：'+(active()?.name||'列表'):'播放顺序：柜内排列');q('[data-pl-rows]').replaceChildren();(l?.entries||[]).forEach((e,i)=>{const row=document.createElement('div');row.className='pl-row';const title=document.createElement('button');title.className='pl-title';title.textContent=(i+1)+'. '+e.title;title.title=e.artist||'';title.onclick=()=>attempt(()=>start(i));row.append(title);for(const [text,label,fn,disabled]of [['↑','上移 '+e.title,()=>move(i,-1),i===0],['↓','下移 '+e.title,()=>move(i,1),i===l.entries.length-1],['换','替换 '+e.title,()=>{replaceIndex=i;draw();},false],['×','移出列表 '+e.title,()=>{remove(i);replaceIndex=null;draw();},false]]){const b=document.createElement('button');b.textContent=text;b.setAttribute('aria-label',label);b.disabled=disabled;b.onclick=()=>attempt(fn);row.append(b);}q('[data-pl-rows]').append(row);});
   catalog=getCatalog();const picker=q('[data-pl-catalog]'),old=picker.value;picker.replaceChildren();catalog.forEach((e,i)=>{const o=document.createElement('option');o.value=i;o.textContent=e.title+' · '+(e.artist||'');picker.append(o);});if(Number(old)<catalog.length)picker.value=old;q('[data-pl-add]').textContent=replaceIndex==null?'加入':'替换';q('[data-pl-cancel]').hidden=replaceIndex==null;q('[data-pl-play]').disabled=!l?.entries.length||playing;
  }
  q('[data-pl-new]').onclick=()=>attempt(()=>{replaceIndex=null;create();});q('[data-pl-select]').onchange=e=>{state.selectedId=e.target.value;replaceIndex=null;changed();};q('[data-pl-rename]').onclick=()=>{const l=selected();if(l){l.name=q('[data-pl-name]').value.trim()||l.name;changed();}};
  q('[data-pl-delete]').onclick=()=>{const id=state.selectedId;state.lists=state.lists.filter(l=>l.id!==id);if(state.activeId===id)state.activeId=null;state.selectedId=state.lists[0]?.id||null;replaceIndex=null;changed();};q('[data-pl-play]').onclick=()=>attempt(()=>start());q('[data-pl-off]').onclick=()=>{state.activeId=null;changed();};q('[data-pl-add]').onclick=()=>attempt(()=>{const e=catalog[Number(q('[data-pl-catalog]').value)];if(!e)throw Error('先选择歌曲');if(replaceIndex==null)add(e);else replace(replaceIndex,e);replaceIndex=null;draw();});q('[data-pl-cancel]').onclick=()=>{replaceIndex=null;draw();};watchers.add(draw);draw();return {refresh:draw,key(id){const l=selected();if(!l?.entries.length)return;if(id==='up'||id==='down'){focusIndex=Math.max(0,Math.min(l.entries.length-1,focusIndex+(id==='up'?-1:1)));const rows=host.querySelectorAll('.pl-row');rows.forEach((r,i)=>r.classList.toggle('pl-focused',i===focusIndex));const container=q('[data-pl-rows]'),row=rows[focusIndex];if(row)container.scrollTop=row.offsetTop-container.offsetTop;}else if(id==='left'||id==='right'){move(focusIndex,id==='left'?-1:1);focusIndex=Math.max(0,Math.min(l.entries.length-1,focusIndex+(id==='left'?-1:1)));}else if(id==='confirm')attempt(()=>start(focusIndex));}};
 }
 const style=document.createElement('style');style.textContent='.playback-list-editor .pl-focused{background:#9aa98055}.playback-list-editor .pl-tools{display:flex;gap:4px;align-items:center;margin:5px 0}.playback-list-editor select,.playback-list-editor input{min-width:0;flex:1;width:0;font:inherit;color:inherit;background:#faf7ed;border:1px solid #9ba493;padding:5px}.playback-list-editor .pl-row{display:flex;gap:2px;align-items:center;border-bottom:1px solid #9ba49344}.playback-list-editor .pl-title{flex:1;min-width:0;overflow:hidden;white-space:nowrap;text-overflow:ellipsis;text-align:left}.playback-list-editor [data-pl-rows]{max-height:230px;overflow:auto}.playback-list-editor [data-pl-status]{margin:3px 0;font-size:12px}.playback-list-editor[data-compact=true]{font-size:12px}.playback-list-editor[data-compact=true] .pl-tools{margin:2px 0}.playback-list-editor[data-compact=true] input,.playback-list-editor[data-compact=true] select{display:block;margin:0!important;min-height:23px!important;padding:2px!important;background:#e0e9b6!important}.playback-list-editor[data-compact=true] button{min-height:23px!important;font-size:12px!important;padding:2px 4px!important}.playback-list-editor[data-compact=true] [data-pl-rows]{height:90px}.playback-list-editor[data-compact=true] [data-pl-name]{height:24px}';document.head.append(style);
 return {state,selected,active,create,add,local,online,remove,move,replace,prune,restore,mount,start,advance,key,save,refresh:emit,select(id){state.selectedId=id;changed();}};
}
