const PRESETS=[
 {id:'pop',name:'流行音乐',style:'studio',bass:2,treble:1,eq:[2,0,-1,1,1]},
 {id:'voice',name:'人声',style:'field',bass:-1,treble:0,eq:[-2,0,2,1,-1]},
 {id:'instrumental',name:'纯音乐',style:'polar',bass:0,treble:1,eq:[0,0,0,1,1]},
 {id:'classical',name:'古典',style:'walnut',bass:0,treble:0,eq:[0,0,0,0,0]}
];
export function createPreferenceCards({props,group,box,label,interactive,M,read,apply,persist,onDraw,onClose,onDirty}){
 const root=group(props,-2.56,.17,4.90);root.rotation.y=-.19;root.name='Listening preference cards';interactive(root,'preferenceCard');
 const cards=[];for(let i=0;i<3;i++){const card=group(root,-.09*i,.095+i*.085,-.035*i);card.rotation.y=-.12+i*.06;box(card,2.44,.095,1.59,0,0,0,M.paper,.025);const print=label(card,i===2?'PREFERENCES / C82':'LISTENING NOTES',2.08,.64,0,.052,0,{mono:true,color:'#655e4e',res:768});print.rotation.x=-Math.PI/2;cards.push({card,print,base:card.position.clone()});}const top=cards[2];
 let custom=[],selectedId='',active=false,applying=false,progress=0,lastPrint='',lastTap=0;
 const style=document.createElement('style');style.textContent='#preference-card{position:fixed;right:24px;top:24px;width:min(390px,calc(100vw - 48px));max-height:calc(100dvh - 48px);overflow:auto;background:#eee6d3;color:#4d5143;border:1px solid #aaa48d;border-radius:5px;padding:20px;z-index:19;font:14px/1.6 system-ui;box-shadow:0 16px 40px #30372526}#preference-card[hidden]{display:none}#preference-card header{display:flex;justify-content:space-between;align-items:center;position:sticky;top:-20px;background:#eee6d3;padding:8px 0}#preference-card h2{font-size:19px;margin:0}#preference-card button,#preference-card input{font:inherit;color:inherit;background:#f9f4e7;border:1px solid #aaa48d;border-radius:4px;padding:8px;min-height:40px}#preference-card input{display:block;width:100%;margin:6px 0}#preference-card .pref-row{display:flex;gap:6px;margin:7px 0;align-items:center}#preference-card .pref-row button:first-child{flex:1;text-align:left}#preference-card .pref-row [aria-pressed=true]{background:#475f50;color:#fff}#preference-card small{display:block;color:#747360}#preference-card p{margin:10px 0}#preference-card [data-current]{white-space:pre-line;border-top:1px solid #aaa48d;border-bottom:1px solid #aaa48d;padding:10px 0}#preference-card :focus-visible{outline:2px solid #a96943;outline-offset:2px}';document.head.append(style);
 const panel=document.createElement('section');panel.id='preference-card';panel.hidden=true;panel.setAttribute('aria-label','听歌偏好卡');panel.innerHTML='<header><h2>听歌偏好卡</h2><button aria-label="收回偏好卡">×</button></header><p data-current></p><h3>偏好组</h3><div data-groups></div><label>新偏好名称<input maxlength="40" data-pref-name placeholder="例如：夜晚听歌"></label><div class="pref-row"><button data-pref-save>记录当前皮肤与均衡器</button></div><p data-message role="status"></p><small>卡片保存皮肤、低音、高音和五段均衡器，切换时音乐继续播放，音量保持当前值。</small>';document.body.append(panel);
 const msg=panel.querySelector('[data-message]'),groups=()=>[...PRESETS,...custom],title=s=>s.styleName||s.style,summary=s=>`${title(s)} · 低音 ${s.bass.toFixed(1)} / 高音 ${s.treble.toFixed(1)} dB\n均衡器 ${s.eq.map(n=>n>0?'+'+n:n).join(' / ')} dB`;
 function redraw(){const current=read();panel.querySelector('[data-current]').textContent='当前偏好：'+summary(current);const list=panel.querySelector('[data-groups]');list.replaceChildren();for(const item of groups()){const row=document.createElement('div');row.className='pref-row';const b=document.createElement('button');b.textContent=item.name;b.setAttribute('aria-pressed',String(item.id===selectedId));b.dataset.prefApply=item.id;b.onclick=async()=>{if(applying)return;applying=true;msg.textContent='正在切换 '+item.name+'…';for(const e of panel.querySelectorAll('button,input'))if(e!==panel.querySelector('header button'))e.disabled=true;try{await apply(item);selectedId=item.id;persist();msg.textContent='已切换 '+item.name;}catch(e){msg.textContent=e.message||'切换未完成，请稍后再试。';}finally{applying=false;redraw();}};row.append(b);if(custom.includes(item)){const remove=document.createElement('button');remove.textContent='删除';remove.setAttribute('aria-label','删除偏好 '+item.name);remove.onclick=()=>{custom=custom.filter(c=>c.id!==item.id);if(selectedId===item.id)selectedId='';persist();redraw();};row.append(remove);}list.append(row);}panel.querySelector('[data-pref-save]').disabled=applying;panel.querySelector('input').disabled=applying;}
 panel.querySelector('[data-pref-save]').onclick=()=>{if(applying)return;if(custom.length>=24){msg.textContent='最多保存 24 组，请先删除不需要的偏好。';return;}const s=read(),name=panel.querySelector('input').value.trim()||'我的偏好 '+(custom.length+1);const item={id:crypto.randomUUID(),name,style:s.style,bass:s.bass,treble:s.treble,eq:[...s.eq]};custom.push(item);selectedId=item.id;persist();msg.textContent='已记录 '+name;panel.querySelector('input').value='';redraw();};
 function close(){if(!active)return;active=false;panel.hidden=true;onClose();onDirty();}panel.querySelector('header button').onclick=close;panel.addEventListener('keydown',e=>{e.stopPropagation();if(e.key==='Escape')close();});panel.addEventListener('keyup',e=>e.stopPropagation());
 function draw(){if(active){redraw();return;}active=true;panel.hidden=false;onDraw(root);redraw();onDirty();}
 return {root,panel,draw,close,tap(){const now=performance.now();if(now-lastTap<360){lastTap=0;draw();}else{lastTap=now;}},snapshot(){return {selectedId,custom:custom.map(c=>({...c,eq:[...c.eq]}))};},restore(s){if(!s)return;custom=(Array.isArray(s.custom)?s.custom:[]).filter(c=>typeof c.id==='string'&&typeof c.name==='string'&&typeof c.style==='string'&&Number.isFinite(c.bass)&&Number.isFinite(c.treble)&&Array.isArray(c.eq)&&c.eq.length===5&&c.eq.every(Number.isFinite)).slice(0,24).map(c=>({id:c.id,name:c.name.slice(0,40),style:c.style,bass:Math.max(-12,Math.min(12,c.bass)),treble:Math.max(-12,Math.min(12,c.treble)),eq:c.eq.map(n=>Math.max(-12,Math.min(12,n)))}));selectedId=groups().some(c=>c.id===s.selectedId)?s.selectedId:'';},update(dt){const target=active?1:0;const step=dt/(active?1.15:1.25);progress=target>progress?Math.min(target,progress+step):Math.max(target,progress-step);const smooth=t=>t*t*(3-2*t),slide=smooth(Math.min(1,progress/.42)),lift=smooth(Math.max(0,(progress-.42)/.58));top.card.position.copy(top.base);top.card.position.z+=slide*1.30+lift*.12;top.card.position.y+=slide*.025+lift*1.35;top.card.rotation.x=lift*1.05;top.card.rotation.z=0;const s=read(),text='PREFERENCE CARD\n'+(groups().find(c=>c.id===selectedId)?.name||'当前设置')+'  /  '+s.styleName+'\nEQ '+s.eq.map(n=>n>0?'+'+n:n).join(' ');if(text!==lastPrint){top.print.userData.setText(text);lastPrint=text;if(active)panel.querySelector('[data-current]').textContent='当前偏好：'+summary(s);}if(progress!==target)onDirty();},get pose(){return {progress,y:top.card.position.y,z:top.card.position.z,tilt:top.card.rotation.x,base:top.base.toArray()};},get active(){return active;},get moving(){return progress!==(active?1:0);}};
}
