import * as THREE from 'three';
export const TAPE_CORE=.27,TAPE_FULL=.585,TAPE_PLANE=.15;
export function tapeRadii(progress){const p=Math.max(0,Math.min(1,progress)),area=TAPE_FULL**2-TAPE_CORE**2;return [Math.sqrt(TAPE_CORE**2+(1-p)*area),Math.sqrt(TAPE_CORE**2+p*area)];}
function tangent(cx,cy,r,gx,gy,side){const dx=gx-cx,dy=gy-cy,d=Math.hypot(dx,dy),k=(r-.095)/d,h=Math.sqrt(1-k*k),ux=dx/d,uy=dy/d;const candidates=[[ux*k-uy*h,uy*k+ux*h],[ux*k+uy*h,uy*k-ux*h]];const n=candidates.sort((a,b)=>side*(b[0]-a[0]))[0];return {n,pack:[cx+(r+.004)*n[0],cy+(r+.004)*n[1]],guide:[gx+.099*n[0],gy+.099*n[1]]};}
export function tapePoints(progress){const radii=tapeRadii(progress),left=tangent(-.84,-.1,radii[0],-1.27,-.7,-1),right=tangent(.84,-.1,radii[1],1.27,-.7,1),points=[];const add=(x,y)=>points.push(new THREE.Vector3(x,y,TAPE_PLANE));add(...left.pack);let start=Math.atan2(left.n[1],left.n[0]),end=-Math.PI/2;while(end<start)end+=Math.PI*2;for(let i=0;i<=24;i++){const a=start+(end-start)*i/24;add(-1.27+.099*Math.cos(a),-.7+.099*Math.sin(a));}start=-Math.PI/2;end=Math.atan2(right.n[1],right.n[0]);while(end<start)end+=Math.PI*2;for(let i=0;i<=24;i++){const a=start+(end-start)*i/24;add(1.27+.099*Math.cos(a),-.7+.099*Math.sin(a));}add(...right.pack);return {points,radii};}
export function updateRibbon(geometry,progress){const {points,radii}=tapePoints(progress),count=points.length;let attr=geometry.getAttribute('position');if(!attr){attr=new THREE.BufferAttribute(new Float32Array(count*4*3),3);geometry.setAttribute('position',attr);const indices=[];for(let i=0;i<count-1;i++)for(let j=0;j<4;j++){const a=i*4+j,b=i*4+(j+1)%4,c=b+4,d=a+4;indices.push(a,b,c,a,c,d);}indices.push(0,2,1,0,3,2,(count-1)*4,(count-1)*4+1,(count-1)*4+2,(count-1)*4,(count-1)*4+2,(count-1)*4+3);for(let i=0;i<indices.length;i+=3)[indices[i+1],indices[i+2]]=[indices[i+2],indices[i+1]];geometry.setIndex(indices);}
for(let i=0;i<count;i++){const before=points[Math.max(0,i-1)],after=points[Math.min(count-1,i+1)],dx=after.x-before.x,dy=after.y-before.y,len=Math.hypot(dx,dy),nx=-dy/len*.004,ny=dx/len*.004;for(let j=0;j<4;j++){const sign=j<2?-1:1;attr.setXYZ(i*4+j,points[i].x+nx*sign,points[i].y+ny*sign,TAPE_PLANE+([0,3].includes(j)?-.04:.04));}}
attr.needsUpdate=true;geometry.computeVertexNormals();geometry.computeBoundingSphere();return radii;}
export function cableCurve(plug,earcup=new THREE.Vector3(4.87,.275,6.8)){
 const path=new THREE.CurvePath(),v=(x,y,z)=>new THREE.Vector3(x,y,z),floor=.215,outer=Math.max(8.98,plug.x+.48),a=plug.clone(),b=v(outer,plug.y,plug.z),c=v(8.98,floor,3.7),d=v(8.98,floor,7.15),e=v(8.55,floor,7.50),f=v(5.50,floor,7.50);
 path.add(new THREE.LineCurve3(a,b));path.add(new THREE.CubicBezierCurve3(b,v(outer+.13,plug.y,plug.z),v(outer+.13,floor,2.65),c));path.add(new THREE.LineCurve3(c,d));path.add(new THREE.CubicBezierCurve3(d,v(8.98,floor,7.42),v(8.82,floor,7.50),e));path.add(new THREE.LineCurve3(e,f));path.add(new THREE.CubicBezierCurve3(f,v(5.10,floor,7.50),v(5.18,earcup.y,earcup.z),earcup.clone()));return path;
}
