import {mountUserGuide} from './user-guide.js';
export function createSettings({read,change,onOpen,onClose,getFolder,chooseFolder}){
 const style=document.createElement('style');style.textContent=`#machine-settings{position:fixed;inset:0;z-index:20;background:#26342e44;display:grid;place-items:center;padding:16px}#machine-settings[hidden]{display:none}#machine-settings article{width:min(410px,100%);max-height:85dvh;overflow:auto;border:1px solid #9aa08d;border-radius:10px;padding:22px;background:#eee9db;color:#303d38;box-shadow:0 16px 50px #26342e33;font:16px/1.6 system-ui}#machine-settings header{display:flex;justify-content:space-between;align-items:center}#machine-settings h2{margin:0;font-size:20px}#machine-settings label{display:grid;grid-template-columns:1fr 155px;align-items:center;gap:16px;margin:20px 0}#machine-settings input{display:block;width:100%;accent-color:#98623d}#machine-settings select,#machine-settings button{font:inherit;min-height:44px;background:#faf6ec;color:inherit;border:1px solid #9aa08d;border-radius:5px;padding:5px 10px}#machine-settings p{font-size:13px;color:#616b5e}#machine-settings :focus-visible{outline:2px solid #98623d;outline-offset:3px}`;document.head.append(style);
 const panel=document.createElement('section');panel.id='machine-settings';panel.hidden=true;panel.innerHTML='<article role="dialog" aria-modal="true" aria-labelledby="settings-title"><header><h2 id="settings-title">螺丝盒 · 设置</h2><button type="button" aria-label="关闭设置">×</button></header><label>音乐音量 <input name="volume" aria-label="音乐音量" type="range" min="0" max="100"></label><label>机械音效 <input name="effects" aria-label="机械音效" type="checkbox"></label><label>播放顺序 <select name="shuffle"><option value="0">顺序播放</option><option value="1">随机播放</option></select></label><label>循环播放 <select name="repeat"><option value="0">不循环</option><option value="1">单曲循环</option><option value="2">列表循环</option></select></label><label>音频输出 <select name="stereo"><option value="0">立体声</option><option value="1">单声道</option></select></label><p>设置会保存在本机，与磁带机上的旋钮和开关联动。</p></article>';document.body.append(panel);
 const output=document.createElement('section');output.innerHTML='<h3>刻录保存文件夹</h3><p role="status" data-folder></p><button type="button" data-choose-folder>更改保存文件夹</button><p>新刻录的 MP3 将按歌手、专辑收进所选文件夹，已有文件不会移动。点击出口的 MP3 下载仍由浏览器或系统分享面板决定保存位置。</p>';panel.querySelector('article').append(output);
 const folderText=output.querySelector('[data-folder]'),folderButton=output.querySelector('button');
 function showFolder(){folderText.textContent=getFolder?.()?'当前文件夹：'+getFolder():'尚未选择自动保存文件夹';if(!window.showDirectoryPicker){folderText.textContent='当前浏览器不支持指定文件夹，请使用刻录机 MP3 按钮，在下载或分享面板中选择保存位置。';folderButton.disabled=true;}}
 folderButton.onclick=async()=>{folderButton.disabled=true;try{await chooseFolder();showFolder();}catch(e){if(e.name!=='AbortError')folderText.textContent='无法使用该文件夹，请重新选择并允许写入。';}finally{folderButton.disabled=!window.showDirectoryPicker;}};
 mountUserGuide(panel.querySelector('article'));
 const guideStyle=document.createElement('style');guideStyle.textContent='#quick-guide{border-top:1px solid #b3b6a5;margin-top:22px;padding-top:16px}#quick-guide summary{cursor:pointer;min-height:44px;font-weight:700}#quick-guide h3{font-size:16px;margin:20px 0 6px}#quick-guide li{margin:8px 0}#quick-guide p,#quick-guide li{font-size:14px;line-height:1.75}#quick-guide ol{padding-left:22px}';document.head.append(guideStyle);
 let previousFocus=null;
 const fields=[...panel.querySelectorAll('input,select')];
 function sync(){showFolder();const values=read();for(const f of fields){if(f.type==='checkbox')f.checked=values[f.name];else f.value=values[f.name];}}
 function close(){if(panel.hidden)return;panel.hidden=true;onClose?.();previousFocus?.focus({preventScroll:true});}
 for(const f of fields)f.addEventListener(f.type==='range'?'input':'change',()=>change(f.name,f.type==='checkbox'?f.checked:Number(f.value)));
 panel.querySelector('button').onclick=close;panel.onclick=e=>{if(e.target===panel)close();};
 panel.addEventListener('keydown',e=>{e.stopPropagation();if(e.key==='Escape'){e.preventDefault();close();}if(e.key==='Tab'){const items=[...panel.querySelectorAll('button:not(:disabled),input,select,summary')],first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});panel.addEventListener('keyup',e=>e.stopPropagation());
 return {get active(){return !panel.hidden;},close,open(){if(!panel.hidden)return;previousFocus=document.activeElement;onOpen?.();sync();panel.hidden=false;panel.querySelector('button').focus({preventScroll:true});}};
}
