import {mountUserGuide} from './user-guide.js';
export function createSettings({read,change,onOpen,onClose,getFolder,chooseFolder,chooseLyrics,getOnlineConfig,setOnlineConfig}){
 const style=document.createElement('style');style.textContent=`#machine-settings{position:fixed;inset:0;z-index:20;background:#26342e44;display:grid;place-items:center;padding:16px}#machine-settings[hidden]{display:none}#machine-settings article{width:min(410px,100%);max-height:85dvh;overflow:auto;border:1px solid #9aa08d;border-radius:10px;padding:22px;background:#eee9db;color:#303d38;box-shadow:0 16px 50px #26342e33;font:16px/1.6 system-ui}#machine-settings header{display:flex;justify-content:space-between;align-items:center}#machine-settings fieldset{border:1px solid #b3b6a5;border-radius:6px;margin:18px 0;padding:0 12px}#machine-settings legend{font-size:14px;padding:0 6px}#machine-settings h2{margin:0;font-size:20px}#machine-settings label{display:grid;grid-template-columns:1fr 155px;align-items:center;gap:16px;margin:20px 0}#machine-settings input{display:block;width:100%;accent-color:#98623d}#machine-settings select,#machine-settings button{font:inherit;min-height:44px;background:#faf6ec;color:inherit;border:1px solid #9aa08d;border-radius:5px;padding:5px 10px}#machine-settings p{font-size:13px;color:#616b5e}#machine-settings :focus-visible{outline:2px solid #98623d;outline-offset:3px}`;document.head.append(style);
 const panel=document.createElement('section');panel.id='machine-settings';panel.hidden=true;panel.innerHTML='<article role="dialog" aria-modal="true" aria-labelledby="settings-title"><header><h2 id="settings-title">螺丝盒 · 设置</h2><button type="button" aria-label="关闭设置">×</button></header><label>画面质感 <select name="renderQuality"><option value="0">标准摄影棚</option><option value="1">摄影 · 接触阴影</option></select></label><p>摄影档增加接触处的阴影，会多用一些显卡资源；手机保留标准档。</p><label>音乐音量 <input name="volume" aria-label="音乐音量" type="range" min="0" max="100"></label><label>机械音效 <input name="effects" aria-label="机械音效" type="checkbox"></label><label>播放顺序 <select name="shuffle"><option value="0">顺序播放</option><option value="1">随机播放</option></select></label><label>循环播放 <select name="repeat"><option value="0">不循环</option><option value="1">单曲循环</option><option value="2">列表循环</option></select></label><label>音频输出 <select name="stereo"><option value="0">立体声</option><option value="1">单声道</option></select></label><p>设置会保存在本机，与磁带机上的旋钮和开关联动。</p></article>';document.body.append(panel);
 const output=document.createElement('section');output.innerHTML='<h3>刻录保存文件夹</h3><p role="status" data-folder></p><button type="button" data-choose-folder>更改保存文件夹</button><p>新刻录的 MP3 将按歌手、专辑收进所选文件夹，已有文件不会移动。点击出口的 MP3 下载仍由浏览器或系统分享面板决定保存位置。</p>';panel.querySelector('article').append(output);
 const folderText=output.querySelector('[data-folder]'),folderButton=output.querySelector('button');
 function showFolder(){folderText.textContent=getFolder?.()?'当前文件夹：'+getFolder():'尚未选择自动保存文件夹';if(!window.showDirectoryPicker){folderText.textContent='当前浏览器不支持指定文件夹，请使用刻录机 MP3 按钮，在下载或分享面板中选择保存位置。';folderButton.disabled=true;}}
 folderButton.onclick=async()=>{folderButton.disabled=true;try{await chooseFolder();showFolder();}catch(e){if(e.name!=='AbortError')folderText.textContent='无法使用该文件夹，请重新选择并允许写入。';}finally{folderButton.disabled=!window.showDirectoryPicker;}};
 const lyricSection=document.createElement('section');lyricSection.innerHTML='<h3>歌词便签</h3><p>导入与音乐文件同名的 LRC，或给已选中的磁带配上一页歌词；带时间标签的歌词随播放同步。单击三角便签切换背景歌词，双击便签聚焦查看；按 L 也可切换背景歌词。</p><label>刻录时在线补全 <input type="checkbox" name="onlineLyrics" aria-label="刻录时在线补全歌词"></label><p>本地歌词优先；打开后，仅向 LRCLIB 发送曲名、歌手、专辑和时长，不上传音频。需要联网，找不到歌词不会阻止刻录；新刻录的 MP3 会携带取得的歌词。</p><button type="button" data-choose-lyrics>导入本地 LRC 歌词</button>';const fontOptions='<option value="serif">书刊衬线</option><option value="sans">清晰无衬线</option><option value="mono">打字机</option><option value="rounded">圆润字体</option>';lyricSection.innerHTML+='<fieldset><legend>便签纸页</legend><label>歌词字号 <input name="lyricPageSize" aria-label="便签歌词字号" type="range" min="0.65" max="1.6" step="0.05"></label><label>歌词字体 <select name="lyricPageFont" data-string aria-label="便签歌词字体">'+fontOptions+'</select></label></fieldset><fieldset><legend>背景歌词</legend><label>文字大小 <input name="lyricBgSize" aria-label="背景歌词大小" type="range" min="0.65" max="1.6" step="0.05"></label><label>文字字体 <select name="lyricBgFont" data-string aria-label="背景歌词字体">'+fontOptions+'</select></label><label>墨色深度 <input name="lyricBgDepth" aria-label="背景歌词墨色深度" type="range" min="0.35" max="2.5" step="0.05"></label></fieldset>';panel.querySelector('article').append(lyricSection);lyricSection.querySelector('button').onclick=()=>chooseLyrics?.();
 const online=document.createElement('section');online.innerHTML='<h3>在线点歌接口</h3><p>Audius 开放曲库可直接搜索播放，曲库与网易、QQ 不同。Meting 模式使用你提供的外部服务；HTML 内嵌搜索和播放模块，不包含音乐平台服务端。</p><label>歌曲来源 <select data-online-provider aria-label="默认在线歌曲来源"><option value="audius">Audius</option><option value="meting">Meting</option></select></label><label>平台 <select data-online-platform aria-label="Meting 音乐平台"><option value="netease">网易</option><option value="tencent">QQ</option><option value="kugou">酷狗</option><option value="kuwo">酷我</option><option value="baidu">百度</option></select></label><input data-online-endpoint type="url" aria-label="Meting 接口地址" placeholder="https://你的服务地址/api.php" maxlength="2048"><p>接口需支持搜索、歌曲地址和跨域访问。只有返回 downloadable=true 的音频才开放下载刻录，不从在线播放链接自动生成实体磁带。</p><button type="button" data-save-online>保存点歌接口</button><p data-online-message role="status"></p>';panel.querySelector('article').append(online);const onlineFields={provider:online.querySelector('[data-online-provider]'),platform:online.querySelector('[data-online-platform]'),endpoint:online.querySelector('[data-online-endpoint]')};onlineFields.endpoint.style.cssText='display:block;width:100%;min-height:44px;font:inherit;padding:8px;background:#faf6ec;color:inherit;border:1px solid #9aa08d;border-radius:5px';online.querySelector('[data-save-online]').onclick=()=>{const values=Object.fromEntries(Object.entries(onlineFields).map(([key,f])=>[key,f.value]));try{if(values.provider==='meting'){const u=new URL(values.endpoint);if(u.protocol!=='https:'&&!(u.protocol==='http:'&&['localhost','127.0.0.1','[::1]'].includes(u.hostname)))throw Error();}setOnlineConfig?.(values);online.querySelector('[data-online-message]').textContent='点歌接口已保存。';}catch{online.querySelector('[data-online-message]').textContent='请填写 HTTPS 接口，或本机服务地址。';}};
 mountUserGuide(panel.querySelector('article'));
 const guideStyle=document.createElement('style');guideStyle.textContent='#quick-guide{border-top:1px solid #b3b6a5;margin-top:22px;padding-top:16px}#quick-guide summary{cursor:pointer;min-height:44px;font-weight:700}#quick-guide h3{font-size:16px;margin:20px 0 6px}#quick-guide li{margin:8px 0}#quick-guide p,#quick-guide li{font-size:14px;line-height:1.75}#quick-guide ol{padding-left:22px}';document.head.append(guideStyle);
 let previousFocus=null;
 const fields=[...panel.querySelectorAll('input[name],select[name]')];
 function sync(){showFolder();const values=read();for(const f of fields){if(f.name==='renderQuality')f.disabled=!values.renderSupported;if(f.type==='checkbox')f.checked=values[f.name];else f.value=values[f.name];}const config=getOnlineConfig?.()||{};for(const [key,f]of Object.entries(onlineFields))f.value=config[key]||'';}
 function close(){if(panel.hidden)return;panel.hidden=true;onClose?.();previousFocus?.focus({preventScroll:true});}
 for(const f of fields)f.addEventListener(f.type==='range'?'input':'change',()=>change(f.name,f.type==='checkbox'?f.checked:f.hasAttribute('data-string')?f.value:Number(f.value)));
 panel.querySelector('button').onclick=close;panel.onclick=e=>{if(e.target===panel)close();};
 panel.addEventListener('keydown',e=>{e.stopPropagation();if(e.key==='Escape'){e.preventDefault();close();}if(e.key==='Tab'){const items=[...panel.querySelectorAll('button:not(:disabled),input,select,summary')],first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});panel.addEventListener('keyup',e=>e.stopPropagation());
 return {get active(){return !panel.hidden;},close,open(){if(!panel.hidden)return;previousFocus=document.activeElement;onOpen?.();sync();panel.hidden=false;panel.querySelector('button').focus({preventScroll:true});}};
}
